import "server-only";

import Link from "next/link";
import { redirect } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createServerSupabaseRSC } from "@shared/lib/supabase/server";
import { getPropertyInspectionTemplate, propertyInspectionTypes, type PropertyInspectionType } from "@/features/property/lib/propertyInspectionTemplates";
import { createPropertyInspection } from "./actions";

type AllowedStatus = "ok" | "fail" | "na";
type DB = { public: { Tables: { profiles: { Row: { id: string; shop_id: string | null } }; property_properties: { Row: { id: string; name: string; shop_id: string } }; property_units: { Row: { id: string; property_id: string; unit_label: string } }; property_inspections: { Row: { id: string }; Insert: { shop_id: string; property_id: string; unit_id: string | null; performed_by_profile_id: string; inspection_type: string; status: string; summary: string | null; findings: unknown; completed_at: string } } } } };
const client = () => createServerSupabaseRSC() as unknown as SupabaseClient<DB>;


export default async function Page({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
 const params = (await searchParams) ?? {}; const type = (propertyInspectionTypes.includes((Array.isArray(params.type) ? params.type[0] : params.type) as PropertyInspectionType) ? (Array.isArray(params.type) ? params.type[0] : params.type) : "move_in") as PropertyInspectionType; const error = Array.isArray(params.error) ? params.error[0] : params.error;
 const template = getPropertyInspectionTemplate(type); const supabase = client(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/sign-in');
 const [{ data: profile }, { data: properties }, { data: units }] = await Promise.all([supabase.from("profiles").select("id,shop_id").eq("id", user.id).maybeSingle(), supabase.from("property_properties").select("id,name").order("name"), supabase.from("property_units").select("id,property_id,unit_label").order("unit_label")]);
 if (!profile?.shop_id) return <main className="p-6 text-[color:var(--theme-text-primary)]">Missing shop context.</main>;
 return <main className="min-h-screen bg-[var(--theme-gradient-panel)] p-6 text-[color:var(--theme-text-primary)]"><div className="mx-auto max-w-6xl"><div className="sticky top-2 z-10 mb-4 rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-overlay)] p-4 backdrop-blur"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">New property inspection</h1><p className="text-sm text-[color:var(--theme-text-secondary)]">Dedicated property inspection — no quote flow</p></div><Link href="/property/inspections" className="text-xs underline">Back</Link></div></div>{error ? <div className="mb-3 rounded border border-rose-400/30 bg-rose-500/10 p-2 text-sm">{error}</div> : null}
 <div className="mb-4 flex gap-2">{propertyInspectionTypes.map((t) => <Link key={t} href={`/property/inspections/new?type=${t}`} className={`rounded-full border px-3 py-1 text-xs ${t===type ? "border-[color:var(--accent-copper)]/70 bg-[color:var(--accent-copper)]/20" : "border-[color:var(--theme-border-soft)]"}`}>{t.replaceAll("_","-")}</Link>)}</div>
 <form action={createPropertyInspection} className="space-y-5"><input type="hidden" name="inspection_type" value={type} /><div className="grid gap-3 rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4 md:grid-cols-3"><select required name="property_id" className="rounded border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-2"><option value="">Select property</option>{(properties??[]).map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="unit_id" className="rounded border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-2"><option value="">No unit</option>{(units??[]).map((u)=><option key={u.id} value={u.id}>{u.unit_label}</option>)}</select><textarea name="summary" rows={2} className="rounded border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-2" placeholder="Summary"/></div>
 <div className="rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4"><h2 className="mb-1 text-sm uppercase tracking-[0.2em] text-[color:var(--theme-text-secondary)]">{template.label}</h2>{template.sections.map((section,si)=><section key={section.title} className="mt-4"><h3 className="border-b border-[color:var(--theme-border-soft)] pb-2 text-sm font-semibold text-amber-200">{section.title}</h3>{section.items.map((item,ii)=><div key={item} className="grid gap-2 border-b border-[color:var(--theme-border-soft)] py-3 md:grid-cols-12 md:items-center"><div className="md:col-span-4 text-sm">{item}</div><div className="md:col-span-3 flex gap-3 text-xs">{(["ok","fail","na"] as AllowedStatus[]).map((s)=><label key={s} className="flex items-center gap-1"><input type="radio" name={`status_${si}_${ii}`} value={s} defaultChecked={s==="ok"}/>{s.toUpperCase()}</label>)}</div><textarea name={`notes_${si}_${ii}`} rows={2} className="md:col-span-3 rounded border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-2 text-xs" placeholder="Notes"/><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" name={`photo_${si}_${ii}`} className="md:col-span-2 text-xs"/></div>)}</section>)}</div>
 <button type="submit" className="rounded-full border border-[color:var(--accent-copper)]/70 bg-[color:var(--accent-copper)]/20 px-5 py-2 text-xs font-semibold uppercase">Create and complete inspection</button></form></div></main>;
}
