export const AI_ACTION_EVENT_TYPES = {
  RECOMMENDATION_CREATED: "recommendation.created",
  RECOMMENDATION_ACKNOWLEDGED: "recommendation.acknowledged",
  RECOMMENDATION_DISMISSED: "recommendation.dismissed",
  RECOMMENDATION_RESOLVED: "recommendation.resolved",
  RECOMMENDATION_EXPIRED: "recommendation.expired",
  RECOMMENDATION_SUPERSEDED: "recommendation.superseded",
  EVIDENCE_SNAPSHOT_CREATED: "evidence_snapshot.created",
  ACTION_PREVIEW_CREATED: "action_preview.created",
  ACTION_PREVIEW_READY: "action_preview.ready",
  ACTION_PREVIEW_CANCELLED: "action_preview.cancelled",
  ACTION_PREVIEW_EXPIRED: "action_preview.expired",
  ACTION_PREVIEW_BLOCKED_EXECUTION: "action_preview.blocked_execution",
  ACTION_APPROVAL_REQUESTED: "action_approval.requested",
  ACTION_APPROVAL_APPROVED: "action_approval.approved",
  ACTION_APPROVAL_REJECTED: "action_approval.rejected",
  ACTION_APPROVAL_EXPIRED: "action_approval.expired",
  ACTION_APPROVAL_CANCELLED: "action_approval.cancelled",
  ACTION_EXECUTION_REQUESTED: "action_execution.requested",
  ACTION_EXECUTION_BLOCKED: "action_execution.blocked",
  ACTION_EXECUTION_STARTED: "action_execution.started",
  ACTION_EXECUTION_SUCCEEDED: "action_execution.succeeded",
  ACTION_EXECUTION_FAILED: "action_execution.failed",
  ACTION_EXECUTION_COMPENSATED: "action_execution.compensated",
} as const;

export type AiActionEventType = (typeof AI_ACTION_EVENT_TYPES)[keyof typeof AI_ACTION_EVENT_TYPES];

export const RECOMMENDATION_EVENT_TYPES = [
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_CREATED,
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_ACKNOWLEDGED,
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_DISMISSED,
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_RESOLVED,
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_EXPIRED,
  AI_ACTION_EVENT_TYPES.RECOMMENDATION_SUPERSEDED,
] as const;

export const EVIDENCE_EVENT_TYPES = [AI_ACTION_EVENT_TYPES.EVIDENCE_SNAPSHOT_CREATED] as const;

export const ACTION_PREVIEW_EVENT_TYPES = [
  AI_ACTION_EVENT_TYPES.ACTION_PREVIEW_CREATED,
  AI_ACTION_EVENT_TYPES.ACTION_PREVIEW_READY,
  AI_ACTION_EVENT_TYPES.ACTION_PREVIEW_CANCELLED,
  AI_ACTION_EVENT_TYPES.ACTION_PREVIEW_EXPIRED,
  AI_ACTION_EVENT_TYPES.ACTION_PREVIEW_BLOCKED_EXECUTION,
] as const;

export const ACTION_APPROVAL_EVENT_TYPES = [
  AI_ACTION_EVENT_TYPES.ACTION_APPROVAL_REQUESTED,
  AI_ACTION_EVENT_TYPES.ACTION_APPROVAL_APPROVED,
  AI_ACTION_EVENT_TYPES.ACTION_APPROVAL_REJECTED,
  AI_ACTION_EVENT_TYPES.ACTION_APPROVAL_EXPIRED,
  AI_ACTION_EVENT_TYPES.ACTION_APPROVAL_CANCELLED,
] as const;

export const ACTION_EXECUTION_EVENT_TYPES = [
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_REQUESTED,
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_BLOCKED,
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_STARTED,
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_SUCCEEDED,
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_FAILED,
  AI_ACTION_EVENT_TYPES.ACTION_EXECUTION_COMPENSATED,
] as const;

const ALL_AI_ACTION_EVENT_TYPES = new Set<string>(Object.values(AI_ACTION_EVENT_TYPES));

export function isAiActionEventType(value: string): value is AiActionEventType {
  return ALL_AI_ACTION_EVENT_TYPES.has(value);
}

export function assertAiActionEventType(value: string): AiActionEventType {
  if (!isAiActionEventType(value)) {
    throw new Error(`Invalid AI action event type: ${value}`);
  }
  return value;
}
