"use client";
import Link from "next/link";
import type { WorkforceTechnicianActivity } from "../lib/activityTypes";
function min(n: number) { return `${Math.max(0, Math.round(n))} min`; }
function time(v: string | null, timezone?: string | null) { if (!v) return "In progress"; return new Intl.DateTimeFormat(undefined,{ hour:"numeric", minute:"2-digit", timeZone: timezone || undefined }).format(new Date(v)); }
const labels: Record<string,string> = { working_on_job:"Working on job", clocked_in_idle:"Waiting for assignment", on_break:"On break", on_lunch:"On lunch", off_shift:"Off shift", shift_ended:"Shift ended" };
export function TechnicianActivityCard({ activity, timezone }: { activity: WorkforceTechnicianActivity; timezone?: string | null }) {
  const shiftElapsed = activity.shiftStartTime ? min(activity.today.shiftMinutes) : "No active shift";
  return <article className="rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4 shadow-card">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-lg font-semibold text-[color:var(--theme-text-primary)]">{activity.employeeName}</h3><p className="text-xs text-[color:var(--theme-text-secondary)]">{activity.employeeEmail || activity.workforceRole || "Workforce"}</p></div><span className="rounded-full border border-orange-400/30 bg-orange-500/10 px-2.5 py-1 text-xs font-semibold text-orange-100">{labels[activity.operationalState] ?? activity.operationalState}</span></div>
    <p className="mt-3 text-sm text-[color:var(--theme-text-secondary)]">Shift: {activity.shiftStartTime ? time(activity.shiftStartTime, timezone) : "Not started"} · {shiftElapsed}</p>
    {activity.currentJob ? <div className="mt-3 rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3"><p className="text-sm font-semibold text-emerald-100">WO {activity.currentJob.workOrderNumber || "In progress"}</p><p className="text-sm text-[color:var(--theme-text-primary)]">{activity.currentJob.lineDescription || "Job line"}</p><p className="text-sm text-[color:var(--theme-text-secondary)]">{activity.currentJob.customerName || "Customer not linked"}</p><p className="text-sm text-[color:var(--theme-text-secondary)]">{activity.currentJob.vehicleLabel || "Vehicle not linked"}</p><p className="mt-2 text-xs text-[color:var(--theme-text-secondary)]">Started job: {time(activity.currentJob.jobStartedAt, timezone)} · {min(activity.currentJob.elapsedMinutes)}</p></div> : <div className="mt-3 rounded-xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-subtle)] p-3 text-sm text-[color:var(--theme-text-secondary)]">No active job</div>}
    <div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="rounded-lg bg-[color:var(--theme-surface-subtle)] p-2"><p className="text-[color:var(--theme-text-secondary)]">Job time</p><p className="text-[color:var(--theme-text-primary)]">{min(activity.today.jobMinutes)}</p></div><div className="rounded-lg bg-[color:var(--theme-surface-subtle)] p-2"><p className="text-[color:var(--theme-text-secondary)]">No active job</p><p className="text-[color:var(--theme-text-primary)]">{min(activity.today.idleMinutes)}</p></div><div className="rounded-lg bg-[color:var(--theme-surface-subtle)] p-2"><p className="text-[color:var(--theme-text-secondary)]">Sold</p><p className="text-[color:var(--theme-text-primary)]">{activity.today.soldLaborHours.toFixed(1)} h</p></div></div>
    {activity.exceptions.length ? <div className="mt-3 flex flex-wrap gap-2">{activity.exceptions.map(e=><span key={e.code} title={e.message} className="rounded-full border border-red-400/30 bg-red-500/10 px-2 py-1 text-[11px] text-red-100">{e.code.replaceAll("_"," ")}</span>)}</div> : null}
    <div className="mt-4 flex flex-wrap gap-2 text-xs">{activity.currentJob ? <Link className="rounded-lg border border-[color:var(--theme-border-soft)] px-3 py-2 text-[color:var(--theme-accent-text)]" href={`/work-orders/${activity.currentJob.workOrderId}`}>Open current work order</Link> : <span className="rounded-lg border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-subtle)] px-3 py-2 text-[color:var(--theme-text-secondary)]">Awaiting assignment</span>}<Link className="rounded-lg border border-[color:var(--theme-border-soft)] px-3 py-2 text-[color:var(--theme-text-primary)]" href={`/dashboard/workforce/attendance?technician=${encodeURIComponent(activity.employeeName)}`}>View technician activity</Link><Link className="rounded-lg border border-[color:var(--theme-border-soft)] px-3 py-2 text-[color:var(--theme-text-primary)]" href="/dashboard/workforce/scheduling">Correct attendance</Link></div>
  </article>;
}
