import Link from "next/link";
import type { ReactNode } from "react";

function cx(...parts: Array<string | false | null | undefined>) { return parts.filter(Boolean).join(" "); }

export function PortalPageHeader({ eyebrow, title, subtitle, actions }: { eyebrow?: string; title: string; subtitle?: string; actions?: ReactNode; }) {
  return <header className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(197,122,74,0.14),rgba(7,10,20,0.7)_55%)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow ? <p className="text-[11px] uppercase tracking-[0.24em] text-neutral-400">{eyebrow}</p> : null}<h1 className="mt-1 text-2xl font-blackops text-[var(--accent-copper-light)] sm:text-3xl">{title}</h1>{subtitle ? <p className="mt-2 max-w-2xl text-sm text-neutral-300">{subtitle}</p> : null}</div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div></header>;
}
export function PortalSectionCard({ title, subtitle, children, right }: { title?: string; subtitle?: string; children: ReactNode; right?: ReactNode; }) {
  return <section className="rounded-2xl border border-white/10 bg-black/25 p-4 backdrop-blur-xl sm:p-5">{(title || right) ? <div className="mb-3 flex items-start justify-between gap-3"><div>{title ? <h2 className="text-sm font-semibold text-neutral-100">{title}</h2> : null}{subtitle ? <p className="mt-1 text-xs text-neutral-400">{subtitle}</p> : null}</div>{right}</div> : null}{children}</section>;
}
export function PortalPrimaryButton({ href, children }: { href: string; children: ReactNode; }) { return <Link href={href} className="inline-flex items-center justify-center rounded-xl bg-[var(--accent-copper)] px-4 py-2 text-sm font-semibold text-black shadow-[0_8px_24px_rgba(197,122,74,0.4)] hover:brightness-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-copper-light)]">{children}</Link>; }
export function PortalSecondaryButton({ href, children }: { href: string; children: ReactNode; }) { return <Link href={href} className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-black/40 px-4 py-2 text-sm font-semibold text-neutral-100 hover:bg-black/60">{children}</Link>; }
export function PortalStatusChip({ label }: { label: string; }) { return <span className="rounded-full border border-[rgba(197,122,74,0.4)] bg-[rgba(197,122,74,0.14)] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f6c8a8]">{label}</span>; }
export function PortalEmptyState({ title, body }: { title: string; body: string; }) { return <div className="rounded-xl border border-dashed border-white/15 bg-black/20 p-4 text-sm"><p className="font-medium text-neutral-200">{title}</p><p className="mt-1 text-neutral-400">{body}</p></div>; }
export function PortalStatCard({ title, value, sub }: { title: string; value: string; sub?: string }) { return <div className="rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-[11px] uppercase tracking-[0.2em] text-neutral-500">{title}</p><p className="mt-1 text-lg font-semibold text-neutral-100">{value}</p>{sub ? <p className="mt-1 text-xs text-neutral-400">{sub}</p> : null}</div>; }
export function PortalActionCard({ href, title, subtitle, prominent = false }: { href: string; title: string; subtitle: string; prominent?: boolean; }) { return <Link href={href} className={cx("group rounded-2xl border p-4 transition", prominent ? "border-[rgba(197,122,74,0.45)] bg-[linear-gradient(150deg,rgba(197,122,74,0.20),rgba(7,10,20,0.7)_58%)]" : "border-white/10 bg-black/25 hover:border-white/20")}><p className="text-sm font-semibold text-neutral-100">{title}</p><p className="mt-1 text-xs text-neutral-400">{subtitle}</p></Link>; }
