import Link from "next/link";
import type { ReactNode } from "react";

function cx(...parts: Array<string | false | null | undefined>) { return parts.filter(Boolean).join(" "); }

export function PortalPageHeader({ eyebrow, title, subtitle, actions }: { eyebrow?: string; title: string; subtitle?: string; actions?: ReactNode; }) {
  return <header className="rounded-3xl border border-[color:var(--theme-border-soft)] bg-[var(--theme-gradient-panel)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow ? <p className="text-[11px] uppercase tracking-[0.24em] text-[color:var(--theme-text-secondary)]">{eyebrow}</p> : null}<h1 className="mt-1 text-2xl font-blackops text-[var(--accent-copper-light)] sm:text-3xl">{title}</h1>{subtitle ? <p className="mt-2 max-w-2xl text-sm text-[color:var(--theme-text-secondary)]">{subtitle}</p> : null}</div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div></header>;
}
export function PortalSectionCard({ title, subtitle, children, right }: { title?: string; subtitle?: string; children: ReactNode; right?: ReactNode; }) {
  return <section className="rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4 backdrop-blur-xl sm:p-5">{(title || right) ? <div className="mb-3 flex items-start justify-between gap-3"><div>{title ? <h2 className="text-sm font-semibold text-[color:var(--theme-text-primary)]">{title}</h2> : null}{subtitle ? <p className="mt-1 text-xs text-[color:var(--theme-text-secondary)]">{subtitle}</p> : null}</div>{right}</div> : null}{children}</section>;
}
export function PortalPrimaryButton({ href, children }: { href: string; children: ReactNode; }) { return <Link href={href} className="inline-flex items-center justify-center rounded-xl bg-[var(--accent-copper)] px-4 py-2 text-sm font-semibold text-[color:var(--theme-text-on-accent)] shadow-[0_8px_24px_rgba(197,122,74,0.4)] hover:brightness-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-copper-light)]">{children}</Link>; }
export function PortalSecondaryButton({ href, children }: { href: string; children: ReactNode; }) { return <Link href={href} className="inline-flex items-center justify-center rounded-xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] px-4 py-2 text-sm font-semibold text-[color:var(--theme-text-primary)] hover:bg-[color:var(--theme-surface-overlay)]">{children}</Link>; }
export function PortalStatusChip({ label }: { label: string; }) { return <span className="rounded-full border border-[rgba(197,122,74,0.4)] bg-[rgba(197,122,74,0.14)] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f6c8a8]">{label}</span>; }
export function PortalEmptyState({ title, body }: { title: string; body: string; }) { return <div className="rounded-xl border border-dashed border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4 text-sm"><p className="font-medium text-[color:var(--theme-text-primary)]">{title}</p><p className="mt-1 text-[color:var(--theme-text-secondary)]">{body}</p></div>; }
export function PortalStatCard({ title, value, sub }: { title: string; value: string; sub?: string }) { return <div className="rounded-2xl border border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] p-4"><p className="text-[11px] uppercase tracking-[0.2em] text-[color:var(--theme-text-muted)]">{title}</p><p className="mt-1 text-lg font-semibold text-[color:var(--theme-text-primary)]">{value}</p>{sub ? <p className="mt-1 text-xs text-[color:var(--theme-text-secondary)]">{sub}</p> : null}</div>; }
export function PortalActionCard({ href, title, subtitle, prominent = false }: { href: string; title: string; subtitle: string; prominent?: boolean; }) { return <Link href={href} className={cx("group rounded-2xl border p-4 transition", prominent ? "border-[rgba(197,122,74,0.45)] bg-[var(--theme-gradient-panel)]" : "border-[color:var(--theme-border-soft)] bg-[color:var(--theme-surface-inset)] hover:border-[color:var(--theme-border-soft)]")}><p className="text-sm font-semibold text-[color:var(--theme-text-primary)]">{title}</p><p className="mt-1 text-xs text-[color:var(--theme-text-secondary)]">{subtitle}</p></Link>; }
