// src/lib/inspection/templates/maintenance50Point.ts

const maintenance50Point: Record<string, string[]> = {
  "Undercarriage": [
    "Exhaust System",
    "Drive Shaft",
    "CV Boots",
    "Suspension",
    "Brake Lines",
    "Fuel Lines",
    "Transmission Mounts",
    "Engine Mounts",
  ],
  "Fluids & Filters": [
    "Engine Oil",
    "Transmission Fluid",
    "Coolant Level",
    "Brake Fluid",
    "Power Steering Fluid",
    "Windshield Washer Fluid",
    "Engine Air Filter",
    "Cabin Air Filter",
    "Fuel Filter",
  ],
  "Engine Bay": [
    "Belts",
    "Hoses",
    "Battery Terminals",
    "Battery Hold Down",
    "Radiator",
    "Cooling Fans",
    "Oil Leaks",
    "Coolant Leaks",
  ],
  "Brakes": [
    "Front Brake Pads",
    "Rear Brake Pads",
    "Rotors",
    "Brake Calipers",
    "Parking Brake Operation",
    "Brake Pedal Travel",
  ],
  "Wheels & Tires": [
    "Tire Pressure",
    "Tire Tread Depth",
    "Wheel Alignment",
    "Wheel Bearings",
    "Rim Condition",
  ],
  "Exterior": [
    "Lights (Headlights, Tail Lights)",
    "Turn Signals",
    "Brake Lights",
    "Windshield",
    "Wipers",
    "Washer Nozzles",
    "Body Condition",
  ],
  "Interior": [
    "Horn Operation",
    "Climate Controls",
    "Heater Function",
    "AC Function",
    "Instrument Cluster",
    "Warning Lights",
    "Seatbelts",
    "Mirrors",
  ],
};

export default maintenance50Point;