import "server-only";
import Link from "next/link";
import { redirect } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createServerSupabaseRSC } from "@shared/lib/supabase/server";

type Finding = { status: "ok"|"fail"|"na" };
type DB={ public:{ Tables:{ property_members:{Row:{id:string;shop_id:string;user_id:string;property_id:string|null;unit_id:string|null}}; property_inspections:{Row:{id:string;shop_id:string;property_id:string;unit_id:string|null;inspection_type:string;status:string;findings:unknown;completed_at:string|null;created_at:string}}; property_properties:{Row:{id:string;name:string}}; property_units:{Row:{id:string;unit_label:string}} }}};
const client=()=>createServerSupabaseRSC() as unknown as SupabaseClient<DB>;
const parse=(v:unknown)=>Array.isArray(v)?v.filter((x):x is Finding=>!!x&&typeof x==="object"&&"status" in x):[];
export default async function Page(){const s=client();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/sign-in'); const {data:m}=await s.from('property_members').select('id,shop_id,user_id,property_id,unit_id').eq('user_id',user.id); if(!(m??[]).length) return <section className='metal-card rounded-3xl p-5'><h1 className='text-2xl'>Inspections</h1><p className='mt-2 text-sm'>No property portal access is assigned to this account.</p></section>;
const shopIds=[...new Set((m??[]).map((x)=>x.shop_id))]; const {data:rows}=await s.from('property_inspections').select('id,shop_id,property_id,unit_id,inspection_type,status,findings,completed_at,created_at').in('shop_id',shopIds).order('created_at',{ascending:false}).limit(100);
const visible=(rows??[]).filter((r)=> (m??[]).some((mm)=>mm.shop_id===r.shop_id && (!mm.property_id||mm.property_id===r.property_id) && (!mm.unit_id||mm.unit_id===r.unit_id)));
const pids=[...new Set(visible.map((r)=>r.property_id))]; const uids=[...new Set(visible.map((r)=>r.unit_id).filter(Boolean))] as string[];
const [p,u]=await Promise.all([pids.length?s.from('property_properties').select('id,name').in('id',pids):Promise.resolve({data:[] as DB['public']['Tables']['property_properties']['Row'][]}),uids.length?s.from('property_units').select('id,unit_label').in('id',uids):Promise.resolve({data:[] as DB['public']['Tables']['property_units']['Row'][]})]);
const pb=new Map((p.data??[]).map((x)=>[x.id,x.name])); const ub=new Map((u.data??[]).map((x)=>[x.id,x.unit_label]));
return <section className='metal-card rounded-3xl p-5'><h1 className='text-2xl text-neutral-100'>Inspections</h1><p className='mt-2 text-sm text-neutral-300'>Review completed and in-progress inspection results for your property access.</p><div className='mt-3 flex flex-wrap gap-2'><Link href='/portal/property/member' className='rounded-lg border border-white/15 px-3 py-2 text-sm text-neutral-200'>Portal home</Link><Link href='/portal/property/member/requests' className='rounded-lg border border-white/15 px-3 py-2 text-sm text-neutral-200'>Maintenance Requests</Link><Link href='/portal/property/member/requests/new' className='rounded-lg border border-cyan-400/30 bg-cyan-500/10 px-3 py-2 text-sm text-cyan-200'>New request</Link></div><div className='mt-4 space-y-2'>{visible.map((r)=>{const fail=parse(r.findings).filter((f)=>f.status==='fail').length; return <article key={r.id} className='rounded-xl border border-white/10 bg-black/20 p-3 text-sm'><div>{r.inspection_type} · {r.status}</div><div className='text-neutral-400'>Property: {pb.get(r.property_id)??'—'} · Unit: {r.unit_id?(ub.get(r.unit_id)??'—'):'—'}</div><div className='text-neutral-500'>Completed: {r.completed_at?new Date(r.completed_at).toLocaleString():'—'} · Created: {new Date(r.created_at).toLocaleString()} · Fail: {fail}</div><Link href={`/portal/property/member/inspections/${r.id}`} className='underline'>Open inspection</Link></article>;})}</div></section>;
}
