import "server-only";
import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createServerSupabaseRSC } from "@shared/lib/supabase/server";

type Photo={storage_bucket:string;storage_path:string;original_filename:string;content_type:string;size_bytes:number;uploaded_at:string};
type Finding={section:string;item:string;status:"ok"|"fail"|"na";notes:string;photos?:Photo[]};
type DB={public:{Tables:{property_members:{Row:{id:string;shop_id:string;user_id:string;property_id:string|null;unit_id:string|null}};property_inspections:{Row:{id:string;shop_id:string;property_id:string;unit_id:string|null;inspection_type:string;status:string;summary:string|null;findings:unknown;completed_at:string|null;created_at:string}};property_properties:{Row:{id:string;name:string}};property_units:{Row:{id:string;unit_label:string}}}}};
const c=()=>createServerSupabaseRSC() as unknown as SupabaseClient<DB>; const parse=(v:unknown):Finding[]=>Array.isArray(v)?v.filter((f):f is Finding=>!!f&&typeof f==='object'&&'section' in f&&'item' in f):[];
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const s=c();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/sign-in'); const {data:m}=await s.from('property_members').select('id,shop_id,user_id,property_id,unit_id').eq('user_id',user.id); if(!(m??[]).length)return <section className='metal-card rounded-3xl p-5'>No property portal access.</section>;
const shopIds=[...new Set((m??[]).map((x)=>x.shop_id))]; const {data:r}=await s.from('property_inspections').select('id,shop_id,property_id,unit_id,inspection_type,status,summary,findings,completed_at,created_at').eq('id',id).in('shop_id',shopIds).maybeSingle();
if(!r || !(m??[]).some((mm)=>mm.shop_id===r.shop_id&&(!mm.property_id||mm.property_id===r.property_id)&&(!mm.unit_id||mm.unit_id===r.unit_id))) return <section className='metal-card rounded-3xl p-5'>Inspection is not visible to this account.</section>;
const [p,u]=await Promise.all([s.from('property_properties').select('id,name').eq('id',r.property_id).maybeSingle(), r.unit_id?s.from('property_units').select('id,unit_label').eq('id',r.unit_id).maybeSingle():Promise.resolve({data:null})]);
const findings=parse(r.findings); const url=new Map<string,string>(); for(const f of findings) for(const ph of f.photos??[]){const res=await s.storage.from(ph.storage_bucket).createSignedUrl(ph.storage_path,600); if(res.data?.signedUrl) url.set(ph.storage_path,res.data.signedUrl);}
return <section className='metal-card rounded-3xl p-5'><h1 className='text-2xl text-neutral-100'>Inspection detail</h1><p className='text-sm text-neutral-300'>{r.inspection_type} · {r.status}</p><p className='text-sm text-neutral-400'>Property: {p.data?.name??'—'} · Unit: {u.data?.unit_label??'—'}</p><p className='text-sm text-neutral-500'>Completed: {r.completed_at?new Date(r.completed_at).toLocaleString():'—'}</p><Link href='/portal/property/member/inspections' className='underline'>Back to inspections</Link><div className='mt-4 space-y-3'>{findings.map((f)=> <article key={`${f.section}-${f.item}`} className={`rounded-lg border p-3 text-sm ${f.status==='fail'?'border-rose-400/30 bg-rose-500/10':'border-white/10 bg-black/20'}`}><div className='font-medium'>{f.section} — {f.item}</div><div>Status: {f.status}</div><div className='text-neutral-400'>{f.notes||'No notes'}</div>{(f.photos??[]).map((ph)=><div key={ph.storage_path} className='mt-2 text-xs'><div>{ph.original_filename} · {ph.content_type}</div>{url.get(ph.storage_path)?<Image src={url.get(ph.storage_path)??''} alt={ph.original_filename} width={320} height={200} unoptimized className='mt-1 rounded border border-white/10 object-cover'/>:null}</div>)}</article>)}</div></section>; }
