-- Follow-up to the anon/authenticated grant lockdown pass in this same PR.
--
-- Postgres grants EXECUTE to the PUBLIC pseudo-role by default when a function
-- or procedure is created, and every role (anon and authenticated included)
-- implicitly holds whatever PUBLIC holds. Revoking anon/authenticated directly
-- is a no-op for any routine that still has its default PUBLIC grant, so this
-- migration revokes PUBLIC specifically for the same routine list.
--
-- Every routine below was verified to also have its own explicit service_role
-- grant, so revoking PUBLIC does not affect service-role-driven backend code
-- paths; the routine owner (postgres) is unaffected by grants entirely. Same
-- three routines (is_admin, field_storage_path_uuid, realtime_conversation_id)
-- excluded for the same RLS-policy reason. Guarded with to_regprocedure() for
-- the same clean-replay reason as the anon/authenticated migration.

do $$
declare
  sig text;
begin
  foreach sig in array array[
    'public.agent_claim_next_message(text,text[])',
    'public.agent_create_action(uuid,text,agent_action_risk,text,jsonb,boolean)',
    'public.agent_job_heartbeat(uuid,text)',
    'public.agent_mark_job_canceled(uuid,text)',
    'public.agent_mark_job_failed(uuid,text,integer)',
    'public.agent_mark_job_succeeded(uuid)',
    'public.agent_mark_message_failed(uuid,text,integer)',
    'public.agent_mark_message_succeeded(uuid,text)',
    'public.ai_automation_touch_updated_at()',
    'public.apply_stock_move_to_snapshot()',
    'public.approve_lines(uuid,uuid[],uuid[],boolean,uuid)',
    'public.assign_default_shop()',
    'public.assign_unassigned_lines(uuid,uuid)',
    'public.assign_wol_shop_id()',
    'public.auto_release_line()',
    'public.bump_profile_last_active_on_message()',
    'public.can_manage_profile(uuid)',
    'public.capture_ai_automation_observation()',
    'public.chat_participants_key(uuid,uuid[])',
    'public.check_plan_limit(text)',
    'public.clear_auth()',
    'public.compute_labor_cost_for_work_order(uuid)',
    'public.compute_parts_cost_for_work_order(uuid)',
    'public.consume_part_request_item_on_picked(uuid,uuid)',
    'public.consume_part_request_item_on_picked(uuid)',
    'public.create_fleet_form_upload(text,text)',
    'public.customers_set_shop_id()',
    'public.customers_set_updated_at()',
    'public.decrement_user_count()',
    'public.decrement_user_count_on_delete()',
    'public.delete_part_request(uuid)',
    'public.enforce_assistant_notification_consistency()',
    'public.enforce_chat_participant_consistency()',
    'public.enforce_conversation_participant_consistency()',
    'public.enforce_invoice_lifecycle()',
    'public.enforce_part_allocation_limits()',
    'public.enforce_portal_notification_consistency()',
    'public.enforce_shop_user_limit()',
    'public.enforce_single_active_tech_shift()',
    'public.enforce_vehicle_shop_matches_customer()',
    'public.enforce_work_order_approval_consistency()',
    'public.enforce_work_order_customer_vehicle_consistency()',
    'public.enforce_work_order_lifecycle()',
    'public._ensure_same_shop(uuid)',
    'public.ensure_same_shop_policies(regclass,text)',
    'public.ensure_self_owned_policies(regclass,text)',
    'public.ensure_user_with_profile(uuid,uuid,text,text)',
    'public.ensure_wo_shop_policies(regclass,text)',
    'public.finalize_shift_from_end_punch()',
    'public.find_menu_item_for_vehicle_service(uuid,integer,text,text,text,text)',
    'public.first_segment_uuid(text)',
    'public.fn_tech_sessions_guard()',
    'public.generate_next_work_order_custom_id(uuid,uuid)',
    'public.generate_work_order_custom_id(uuid,uuid)',
    'public.get_default_stock_location(uuid)',
    'public.get_live_invoice_id(uuid)',
    'public.get_or_create_vehicle_signature(uuid,uuid)',
    'public.get_or_create_vehicle_signature(uuid,uuid,integer,text,text,text,text,text,text,text)',
    'public.guard_financially_locked_work_order()',
    'public.guard_financially_locked_work_order_child()',
    'public.guard_invoice_version_reissue()',
    'public.handle_approval_to_work_order()',
    'public.handle_new_user()',
    'public.increment_portal_campaign_verified()',
    'public.increment_user_count()',
    'public.inspections_set_shop_id()',
    'public.invoice_is_locked(text,timestamp with time zone)',
    'public.is_customer(uuid)',
    'public.log_ai_event()',
    'public.log_audit()',
    'public.log_work_order_line_history()',
    'public.mark_active()',
    'public.maybe_release_line_hold_for_parts(uuid)',
    'public.menu_item_parts_set_defaults()',
    'public.menu_items_compute_totals()',
    'public.mobile_actor_is_field_operator(uuid,uuid)',
    'public.normalize_work_order_line_status()',
    'public.on_part_request_item_approved_reserve_stock()',
    'public.on_part_request_item_reserved_autopick()',
    'public.on_part_request_items_recheck_line_hold()',
    'public.on_work_order_line_active_parts_flow()',
    'public.on_work_order_line_became_active_create_parts()',
    'public.owner_report_summaries_touch_updated_at()',
    'public.parts_get_operation_result(uuid,text)',
    'public.parts_record_operation(uuid,text,text,uuid,uuid,jsonb)',
    'public.parts_request_jwt_role()',
    'public.parts_validate_replacement_links()',
    'public.phase1_touch_updated_at()',
    'public.portal_approve_line(uuid)',
    'public.portal_approve_part_request_item(uuid)',
    'public.portal_decline_line(uuid)',
    'public.portal_decline_part_request_item(uuid)',
    'public.portal_list_approvals()',
    'public.prevent_finalized_inspection_mutation()',
    'public.prevent_inspection_canonical_marker_mutation()',
    'public.prevent_inspection_signature_evidence_mutation()',
    'public.prevent_part_request_item_anchor_changes()',
    'public.prevent_profile_authorization_self_write()',
    'public.prevent_technician_signature_mutation()',
    'public.profixiq_workforce_role()',
    'public.punch_events_set_user_from_shift()',
    'public.punch_in(uuid)',
    'public.punch_out(uuid)',
    'public.recalc_shop_active_user_count(uuid)',
    'public.recompute_work_order_status(uuid)',
    'public.recompute_wo_status_trigger_func()',
    'public.record_video_metric(uuid,uuid,text,date,integer,integer,numeric,numeric,integer,integer,integer,integer,integer,integer,integer,numeric,jsonb)',
    'public.register_job_photo_storage_object()',
    'public.reserve_part_request_items_for_line(uuid,uuid)',
    'public.reserve_part_request_items_for_line(uuid)',
    'public.restock_consumed_part_request_item(uuid,numeric)',
    'public.restock_consumed_part_request_item(uuid,numeric,uuid)',
    'public.seed_default_hours(uuid)',
    'public.set_authenticated(uuid)',
    'public.set_current_shop_id_from_row()',
    'public.set_import_job_updated_at()',
    'public.set_last_active_now()',
    'public.set_message_edited_at()',
    'public.set_owner_shop_id()',
    'public.set_shop_profiles_updated_at()',
    'public.set_shop_ratings_updated_at()',
    'public.set_updated_at()',
    'public.set_updated_at_work_order_quote_lines()',
    'public.set_wol_shop_id()',
    'public.set_wol_shop_id_from_wo()',
    'public.set_work_order_intelligence_updated_at()',
    'public.set_work_order_line_labor_segments_updated_at()',
    'public.shop_assistant_set_updated_at()',
    'public.shop_assistant_touch_thread_after_message()',
    'public.shop_assistant_validate_action_thread()',
    'public.shop_assistant_validate_message_thread()',
    'public.shop_reel_settings_set_updated_at()',
    'public.shop_staff_user_count(uuid)',
    'public.snapshot_line_on_complete()',
    'public.snapshot_wol_on_wo_complete()',
    'public.sync_profiles_user_id()',
    'public.tg_invoices_compute_totals()',
    'public.tg_invoices_sync_work_orders()',
    'public.tg_log_part_fitment_event_from_allocation()',
    'public.tg_log_part_fitment_event_from_consumption()',
    'public.tg_notify_quote_request()',
    'public.tg_profiles_enforce_shop_user_limit()',
    'public.tg_profiles_recalc_shop_user_count()',
    'public.tg_recompute_shop_rating()',
    'public.tg_set_created_by()',
    'public.tg_set_quoted_at()',
    'public.tg_set_timestamps()',
    'public.tg_set_work_orders_shop()',
    'public.tg_shop_reviews_set_updated_at()',
    'public.tg_shops_set_owner_and_creator()',
    'public.tg_work_orders_sync_vehicle_snapshot()',
    'public.touch_conversation_from_message()',
    'public.transition_booking_status_by_staff(uuid,text)',
    'public.trg_part_request_item_picked_consume()',
    'public.trg_parts_auto_release_approved_line()',
    'public.trg_parts_auto_release_approved_line_part()',
    'public.trg_parts_protect_handoff_boundary()',
    'public.trg_parts_reconcile_line_approval()',
    'public.trg_parts_reconcile_quote_decision()',
    'public.trg_parts_reconcile_request_from_item()',
    'public.trg_parts_reconcile_request_from_parent()',
    'public.trg_parts_require_request_release_for_allocation()',
    'public.trg_parts_require_request_release_for_item_operation()',
    'public.trg_parts_require_request_release_for_po_line()',
    'public.trg_parts_require_request_release_for_wop()',
    'public.trg_parts_sync_technician_ready_from_item()',
    'public.trg_parts_sync_technician_ready_from_request()',
    'public.trg_sync_flat_rate_credits()',
    'public.trg_sync_flat_rate_credits_from_assignment()',
    'public.trg_sync_quote_line_pricing_from_parts()',
    'public.unreserve_part_request_item(uuid,numeric)',
    'public.unreserve_part_request_item(uuid,numeric,uuid)',
    'public.update_part_quote(uuid,uuid,text,numeric)',
    'public.update_updated_at_column()',
    'public.validate_property_approval_thresholds_tenant_consistency()',
    'public.validate_property_request_receipt_scope()',
    'public.validate_work_order_media_scope()',
    'public.vehicles_set_shop_id()',
    'public.wo_alloc_recompute_invoice_aiu()',
    'public.wol_assign_line_no()',
    'public.wol_backfill_template_from_menu()',
    'public.wol_copy_menu_parts_to_work_order_parts()',
    'public.wol_delete_staged_parts_on_delete()',
    'public.wol_recompute_invoice_aiu()',
    'public.wol_refresh_staged_parts_on_update()',
    'public.wol_set_shop_id()',
    'public.wopa_sync_work_order_id()',
    'public.work_order_in_my_shop(uuid)',
    'public.work_order_lines_set_shop_id()',
    'public.work_orders_set_shop_id()'
  ]
  loop
    if to_regprocedure(sig) is not null then
      execute format('revoke execute on routine %s from public', sig);
    end if;
  end loop;
end
$$;
