-- P0-008: canonical runtime schema recovery snapshot (shape layer).
--
-- Generated from read-only production catalog metadata on 2026-07-25, then
-- constrained to relations referenced by runtime code plus their FK dependencies.
-- This migration contains no data writes. Existing relations/types remain unchanged.
-- Constraints, behavior, and authorization are applied in subsequent migrations.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '15min';

DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_action_risk') THEN CREATE TYPE public.agent_action_risk AS ENUM ('low', 'medium', 'high'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_action_status') THEN CREATE TYPE public.agent_action_status AS ENUM ('proposed', 'awaiting_approval', 'approved', 'rejected', 'executing', 'succeeded', 'failed', 'canceled'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_job_kind') THEN CREATE TYPE public.agent_job_kind AS ENUM ('notify_discord', 'analyze_request', 'create_issue_pr', 'run_checks', 'apply_fix'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_job_status') THEN CREATE TYPE public.agent_job_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'canceled', 'dead'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_message_direction') THEN CREATE TYPE public.agent_message_direction AS ENUM ('to_agent', 'to_user'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_request_intent') THEN CREATE TYPE public.agent_request_intent AS ENUM ('feature_request', 'bug_report', 'inspection_catalog_add', 'service_catalog_add', 'refactor'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_request_status') THEN CREATE TYPE public.agent_request_status AS ENUM ('submitted', 'in_progress', 'awaiting_approval', 'approved', 'rejected', 'failed', 'merged'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'ai_training_source') THEN CREATE TYPE public.ai_training_source AS ENUM ('quote', 'appointment', 'inspection', 'work_order', 'customer', 'vehicle'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'analytics_event_type') THEN CREATE TYPE public.analytics_event_type AS ENUM ('impression', 'view', 'click', 'like', 'comment', 'share', 'save', 'watch_time', 'engagement', 'rank', 'lead', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'brand_asset_kind') THEN CREATE TYPE public.brand_asset_kind AS ENUM ('logo', 'icon', 'wordmark', 'badge', 'favicon', 'watermark'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'brand_source_app') THEN CREATE TYPE public.brand_source_app AS ENUM ('profixiq', 'shopreel'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_asset_type') THEN CREATE TYPE public.content_asset_type AS ENUM ('image', 'video', 'audio', 'document', 'thumbnail', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_piece_type') THEN CREATE TYPE public.content_piece_type AS ENUM ('idea', 'hook', 'title', 'caption', 'script', 'voiceover', 'blog', 'seo_meta', 'cta', 'hashtags', 'faq', 'platform_copy'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_source_type') THEN CREATE TYPE public.content_source_type AS ENUM ('inspection', 'inspection_item', 'work_order', 'work_order_line', 'vehicle_media', 'manual', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_status') THEN CREATE TYPE public.content_status AS ENUM ('draft', 'queued', 'processing', 'ready', 'published', 'failed', 'archived'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_type') THEN CREATE TYPE public.content_type AS ENUM ('workflow_demo', 'repair_story', 'inspection_highlight', 'before_after', 'educational_tip', 'how_to', 'findings_on_vehicle', 'blog_post', 'faq', 'google_business_post', 'email_snippet', 'social_post'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'fitment_event_type') THEN CREATE TYPE public.fitment_event_type AS ENUM ('allocated', 'consumed'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'fleet_program_cadence') THEN CREATE TYPE public.fleet_program_cadence AS ENUM ('monthly', 'quarterly', 'mileage_based', 'hours_based'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'inspection_item_status') THEN CREATE TYPE public.inspection_item_status AS ENUM ('ok', 'fail', 'na', 'recommend'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'inspection_status') THEN CREATE TYPE public.inspection_status AS ENUM ('new', 'in_progress', 'paused', 'completed', 'aborted'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'job_type_enum') THEN CREATE TYPE public.job_type_enum AS ENUM ('diagnosis', 'inspection', 'maintenance', 'repair'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'part_request_item_status') THEN CREATE TYPE public.part_request_item_status AS ENUM ('requested', 'quoted', 'awaiting_customer_approval', 'approved', 'reserved', 'picking', 'picked', 'ordered', 'partially_received', 'received', 'consumed', 'cancelled', 'partially_ordered', 'partially_consumed', 'partially_returned', 'returned'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'part_request_status') THEN CREATE TYPE public.part_request_status AS ENUM ('requested', 'quoted', 'approved', 'fulfilled', 'rejected', 'cancelled', 'partially_ordered', 'partially_consumed', 'partially_returned', 'returned', 'deferred'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'plan_t') THEN CREATE TYPE public.plan_t AS ENUM ('free', 'diy', 'pro', 'pro_plus', 'complete_10', 'complete_50', 'complete_100', 'complete_unlimited'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'publication_status') THEN CREATE TYPE public.publication_status AS ENUM ('draft', 'queued', 'publishing', 'published', 'failed', 'skipped'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'publish_platform') THEN CREATE TYPE public.publish_platform AS ENUM ('instagram_reels', 'facebook', 'youtube_shorts', 'tiktok', 'blog', 'linkedin', 'google_business', 'email'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'punch_event_type') THEN CREATE TYPE public.punch_event_type AS ENUM ('start', 'break_start', 'break_end', 'lunch_start', 'lunch_end', 'end'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'quote_request_status') THEN CREATE TYPE public.quote_request_status AS ENUM ('pending', 'in_progress', 'done'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shift_status') THEN CREATE TYPE public.shift_status AS ENUM ('active', 'ended'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_draft_status') THEN CREATE TYPE public.shopreel_draft_status AS ENUM ('draft', 'in_review', 'approved'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_opportunity_action') THEN CREATE TYPE public.shopreel_opportunity_action AS ENUM ('accepted', 'dismissed', 'generated'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_opportunity_status') THEN CREATE TYPE public.shopreel_opportunity_status AS ENUM ('new', 'accepted', 'dismissed', 'generated'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'stock_move_reason') THEN CREATE TYPE public.stock_move_reason AS ENUM ('receive', 'adjust', 'consume', 'return', 'transfer_out', 'transfer_in', 'wo_allocate', 'wo_release', 'seed'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'user_role_enum') THEN CREATE TYPE public.user_role_enum AS ENUM ('owner', 'admin', 'manager', 'mechanic', 'advisor', 'parts', 'customer', 'driver', 'dispatcher', 'fleet_manager', 'foreman', 'lead_hand', 'service', 'unknown'); END IF; END $p0_008$;
CREATE SEQUENCE IF NOT EXISTS public.agent_job_events_id_seq;
CREATE TABLE IF NOT EXISTS public.agent_actions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  request_id uuid NOT NULL,
  kind text NOT NULL,
  risk agent_action_risk DEFAULT 'low'::agent_action_risk NOT NULL,
  summary text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  requires_approval boolean DEFAULT true NOT NULL,
  status agent_action_status DEFAULT 'proposed'::agent_action_status NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejected_reason text,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 10 NOT NULL,
  run_after timestamp with time zone DEFAULT now() NOT NULL,
  last_error text,
  last_error_at timestamp with time zone,
  result jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.agent_attachments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  agent_request_id uuid NOT NULL,
  storage_path text NOT NULL,
  public_url text NOT NULL,
  kind text DEFAULT 'screenshot'::text NOT NULL,
  caption text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.agent_jobs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  request_id uuid,
  kind agent_job_kind NOT NULL,
  status agent_job_status DEFAULT 'queued'::agent_job_status NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 12 NOT NULL,
  run_after timestamp with time zone DEFAULT now() NOT NULL,
  locked_by text,
  locked_at timestamp with time zone,
  heartbeat_at timestamp with time zone,
  last_error text,
  last_error_at timestamp with time zone,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  result jsonb,
  logs_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.agent_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid,
  reporter_id uuid,
  reporter_role text,
  description text NOT NULL,
  intent agent_request_intent DEFAULT 'feature_request'::agent_request_intent,
  normalized_json jsonb DEFAULT '{}'::jsonb,
  github_issue_number integer,
  github_issue_url text,
  github_pr_number integer,
  github_pr_url text,
  github_branch text,
  github_commit_sha text,
  llm_model text,
  llm_confidence numeric(4,3),
  llm_notes text,
  status agent_request_status DEFAULT 'submitted'::agent_request_status NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  run_id uuid
);
CREATE TABLE IF NOT EXISTS public.agent_runs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL,
  goal text NOT NULL,
  idempotency_key text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ai_action_previews (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  recommendation_id uuid,
  domain text NOT NULL,
  action_type text NOT NULL,
  subject_type text NOT NULL,
  subject_id uuid,
  status text DEFAULT 'draft'::text NOT NULL,
  preview_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  intended_mutations jsonb DEFAULT '[]'::jsonb NOT NULL,
  affected_records jsonb DEFAULT '[]'::jsonb NOT NULL,
  side_effects jsonb DEFAULT '[]'::jsonb NOT NULL,
  compensation_plan jsonb DEFAULT '{}'::jsonb NOT NULL,
  idempotency_key text,
  requires_approval boolean DEFAULT true NOT NULL,
  requires_owner_pin boolean DEFAULT false NOT NULL,
  risk_tier text DEFAULT 'medium'::text NOT NULL,
  evidence_snapshot_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ai_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid,
  user_id uuid,
  event_type text NOT NULL,
  entity_id uuid,
  entity_table text,
  payload jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  training_source ai_training_source,
  source_id uuid,
  vehicle_ymm text
);
CREATE TABLE IF NOT EXISTS public.ai_evidence_snapshots (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  subject_type text NOT NULL,
  subject_id uuid,
  domain text NOT NULL,
  evidence_kind text NOT NULL,
  snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
  source_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
  missing_data jsonb DEFAULT '[]'::jsonb NOT NULL,
  freshness_at timestamp with time zone,
  confidence numeric(5,4),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ai_recommendations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  domain text NOT NULL,
  recommendation_type text NOT NULL,
  subject_type text NOT NULL,
  subject_id uuid,
  title text NOT NULL,
  summary text,
  status text DEFAULT 'open'::text NOT NULL,
  priority text DEFAULT 'normal'::text NOT NULL,
  confidence numeric(5,4),
  risk_tier text DEFAULT 'low'::text NOT NULL,
  evidence_snapshot_id uuid,
  evidence_snapshot_ids uuid[] DEFAULT '{}'::uuid[] NOT NULL,
  missing_data jsonb DEFAULT '[]'::jsonb NOT NULL,
  recommended_action jsonb DEFAULT '{}'::jsonb NOT NULL,
  side_effects jsonb DEFAULT '[]'::jsonb NOT NULL,
  requires_approval boolean DEFAULT false NOT NULL,
  requires_owner_pin boolean DEFAULT false NOT NULL,
  source text DEFAULT 'system'::text NOT NULL,
  source_run_id uuid,
  created_by uuid,
  assigned_to uuid,
  dismissed_by uuid,
  dismissed_at timestamp with time zone,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ai_suggestion_feedback (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  work_order_id uuid NOT NULL,
  work_order_line_id uuid,
  suggestion_id text,
  title text NOT NULL,
  labor_hours numeric,
  parts jsonb DEFAULT '[]'::jsonb NOT NULL,
  accepted boolean NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ai_training_data (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid,
  source_event_id uuid,
  content text NOT NULL,
  embedding vector(1536),
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.assets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  uploaded_by uuid,
  storage_bucket text,
  storage_path text,
  public_url text,
  mime_type text,
  asset_type text DEFAULT 'video'::text NOT NULL,
  source text DEFAULT 'upload'::text NOT NULL,
  duration_seconds numeric(10,2),
  width integer,
  height integer,
  size_bytes bigint,
  meta jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.assistant_daily_summaries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL,
  summary_date date DEFAULT CURRENT_DATE NOT NULL,
  summary_text text NOT NULL,
  action_items jsonb DEFAULT '[]'::jsonb NOT NULL,
  links jsonb DEFAULT '[]'::jsonb NOT NULL,
  notifications jsonb DEFAULT '[]'::jsonb NOT NULL,
  source_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.content_assets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  content_event_id uuid NOT NULL,
  asset_type content_asset_type NOT NULL,
  storage_bucket text,
  storage_path text,
  public_url text,
  mime_type text,
  file_name text,
  file_size_bytes bigint,
  duration_seconds numeric(10,2),
  width integer,
  height integer,
  sort_order integer DEFAULT 0 NOT NULL,
  is_primary boolean DEFAULT false NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  asset_id uuid NOT NULL
);
CREATE TABLE IF NOT EXISTS public.content_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  source_type content_source_type NOT NULL,
  source_id uuid,
  content_type content_type NOT NULL,
  title text,
  summary text,
  status content_status DEFAULT 'draft'::content_status NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  vehicle_id uuid,
  customer_id uuid,
  work_order_id uuid,
  work_order_line_id uuid,
  inspection_id uuid,
  ai_prompt_version text,
  needs_review boolean DEFAULT true NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  ai_event_id uuid
);
CREATE TABLE IF NOT EXISTS public.content_pieces (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  content_event_id uuid NOT NULL,
  piece_type content_piece_type NOT NULL,
  platform publish_platform,
  title text,
  slug text,
  body_text text,
  body_markdown text,
  body_json jsonb,
  excerpt text,
  seo_title text,
  seo_description text,
  language_code text DEFAULT 'en'::text,
  tone text,
  version_no integer DEFAULT 1 NOT NULL,
  is_current boolean DEFAULT true NOT NULL,
  status content_status DEFAULT 'draft'::content_status NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  generated_by_ai boolean DEFAULT true NOT NULL,
  model_name text,
  prompt_version text,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.content_platform_accounts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  platform publish_platform NOT NULL,
  account_label text,
  platform_account_id text,
  platform_username text,
  connection_active boolean DEFAULT false NOT NULL,
  access_token_encrypted text,
  refresh_token_encrypted text,
  token_expires_at timestamp with time zone,
  scopes text[] DEFAULT '{}'::text[] NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  last_connected_at timestamp with time zone,
  last_sync_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.content_publications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  content_event_id uuid NOT NULL,
  content_piece_id uuid,
  content_asset_id uuid,
  platform_account_id uuid,
  platform publish_platform NOT NULL,
  status publication_status DEFAULT 'draft'::publication_status NOT NULL,
  scheduled_for timestamp with time zone,
  published_at timestamp with time zone,
  platform_post_id text,
  platform_post_url text,
  caption text,
  title text,
  error_code text,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.content_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  description text,
  default_hook text,
  default_cta text,
  script_guidance text,
  visual_guidance text,
  is_system boolean DEFAULT false NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  name text,
  phone text,
  email text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name text,
  phone_number text,
  address text,
  city text,
  province text,
  postal_code text,
  street text,
  shop_id uuid,
  vehicle text,
  business_name text,
  is_fleet boolean DEFAULT false NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  source_intake_id uuid,
  source_row_id uuid,
  external_id text,
  import_confidence numeric,
  import_notes text,
  customer_since timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public.dashboard_layouts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid,
  layout jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.dashboard_user_layouts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  shop_id uuid,
  scope text DEFAULT 'desktop'::text NOT NULL,
  layout jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  category text DEFAULT 'general'::text NOT NULL,
  vendor_name text,
  description text,
  amount numeric(12,2) DEFAULT 0 NOT NULL,
  tax_amount numeric(12,2) DEFAULT 0 NOT NULL,
  expense_date date DEFAULT CURRENT_DATE NOT NULL,
  work_order_id uuid,
  invoice_ref text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_dispatch_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  driver_profile_id uuid NOT NULL,
  route_label text,
  next_pretrip_due timestamp with time zone,
  state text DEFAULT 'pretrip_due'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  driver_name text,
  unit_label text,
  vehicle_identifier text,
  fleet_id uuid NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_inspection_schedules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  interval_days integer DEFAULT 365 NOT NULL,
  last_inspection_date date,
  next_inspection_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  fleet_id uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_pretrip_reports (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  driver_profile_id uuid,
  driver_name text NOT NULL,
  inspection_date date DEFAULT CURRENT_DATE NOT NULL,
  odometer_km numeric(10,1),
  checklist jsonb NOT NULL,
  notes text,
  has_defects boolean DEFAULT false NOT NULL,
  source text DEFAULT 'mobile_pretrip'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  fleet_id uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_program_tasks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  program_id uuid NOT NULL,
  display_order integer DEFAULT 0 NOT NULL,
  description text NOT NULL,
  job_type text DEFAULT 'maintenance'::text NOT NULL,
  default_labor_hours numeric(5,2),
  section_key text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_programs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  fleet_id uuid NOT NULL,
  name text NOT NULL,
  cadence fleet_program_cadence NOT NULL,
  interval_km integer,
  interval_hours integer,
  interval_days integer,
  base_template_slug text,
  include_custom_inspection boolean DEFAULT false NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_service_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  source_pretrip_id uuid,
  title text NOT NULL,
  summary text NOT NULL,
  severity text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  scheduled_for_date date,
  work_order_id uuid,
  created_by_profile_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  fleet_id uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleet_vehicles (
  fleet_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  active boolean DEFAULT true NOT NULL,
  nickname text,
  custom_interval_km integer,
  custom_interval_hours integer,
  custom_interval_days integer,
  shop_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.fleets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  name text NOT NULL,
  contact_name text,
  contact_email text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.guided_onboarding_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  session_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  step_key text,
  event_type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.guided_onboarding_sessions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  created_by uuid,
  status text DEFAULT 'active'::text NOT NULL,
  current_step_key text,
  summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  completed_at timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public.guided_onboarding_steps (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  session_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  step_key text NOT NULL,
  status text DEFAULT 'not_started'::text NOT NULL,
  destination_path text NOT NULL,
  highlight_key text NOT NULL,
  skipped_reason text,
  summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  error text,
  retry_count integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  completed_at timestamp with time zone,
  answer jsonb DEFAULT '{}'::jsonb NOT NULL,
  question text NOT NULL,
  cta_label text,
  skip_label text,
  sort_order integer,
  skipped_at timestamp with time zone,
  started_at timestamp with time zone,
  title text NOT NULL,
  description text
);
CREATE TABLE IF NOT EXISTS public.inspection_result_items (
  result_id uuid NOT NULL,
  section_title text,
  item_label text,
  status inspection_item_status,
  value text,
  unit text,
  notes text,
  photo_urls jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inspection_results (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  session_id uuid NOT NULL,
  work_order_line_id uuid NOT NULL,
  template_name text,
  customer jsonb,
  vehicle jsonb,
  sections jsonb NOT NULL,
  quote jsonb DEFAULT '[]'::jsonb,
  finished_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inspection_sessions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  work_order_id uuid,
  state jsonb,
  updated_at timestamp without time zone DEFAULT now(),
  work_order_line_id uuid,
  vehicle_id uuid,
  customer_id uuid,
  template text,
  created_by uuid,
  completed_at timestamp with time zone,
  status text DEFAULT 'new'::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inspection_smart_match_feedback (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid,
  item_label text,
  note text,
  suggested_match_id text,
  suggested_label text,
  menu_repair_item_id uuid,
  action text NOT NULL,
  vehicle_year integer,
  vehicle_make text,
  vehicle_model text,
  engine text,
  drivetrain text,
  transmission text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inspection_smart_match_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  inspection_id uuid,
  work_order_id uuid,
  section_title text,
  item_label text,
  note text,
  matched_label text,
  correction text,
  labor_hours numeric,
  parts jsonb,
  confidence numeric,
  menu_repair_item_id uuid,
  created_work_order_line_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  vehicle_year integer,
  vehicle_make text,
  vehicle_model text,
  engine text,
  drivetrain text,
  transmission text
);
CREATE TABLE IF NOT EXISTS public.inspection_template_suggestions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  template_key text,
  name text NOT NULL,
  items jsonb DEFAULT '{}'::jsonb NOT NULL,
  applies_to text DEFAULT 'both'::text NOT NULL,
  confidence numeric DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inspection_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  template_name text NOT NULL,
  sections jsonb NOT NULL,
  description text,
  tags text[],
  vehicle_type text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  labor_hours numeric(5,2),
  shop_id uuid
);
CREATE TABLE IF NOT EXISTS public.inspections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  vehicle_id uuid,
  template_id uuid,
  inspection_type text,
  completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location text,
  status text DEFAULT 'not_started'::text NOT NULL,
  started_at timestamp with time zone,
  summary jsonb,
  photo_urls text[],
  pdf_url text,
  quote_id uuid,
  notes text,
  ai_summary text,
  is_draft boolean DEFAULT true,
  shop_id uuid NOT NULL,
  work_order_id uuid,
  finalized_at timestamp with time zone,
  finalized_by uuid,
  locked boolean DEFAULT false,
  pdf_storage_path text,
  work_order_line_id uuid,
  signing_cycle bigint DEFAULT 0 NOT NULL,
  reopened_at timestamp with time zone,
  reopened_by uuid,
  reopen_reason text,
  is_canonical boolean DEFAULT false NOT NULL,
  sync_revision bigint DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS public.invoice_documents (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  invoice_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  kind text NOT NULL,
  storage_bucket text DEFAULT 'inspection_pdfs'::text NOT NULL,
  storage_path text NOT NULL,
  mime_type text DEFAULT 'application/pdf'::text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.invoice_versions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  work_order_id uuid NOT NULL,
  invoice_id uuid,
  version_number integer NOT NULL,
  lifecycle_status text DEFAULT 'issued'::text NOT NULL,
  currency text NOT NULL,
  subtotal numeric(14,2) DEFAULT 0 NOT NULL,
  discount_total numeric(14,2) DEFAULT 0 NOT NULL,
  tax_total numeric(14,2) DEFAULT 0 NOT NULL,
  total numeric(14,2) DEFAULT 0 NOT NULL,
  paid_total numeric(14,2) DEFAULT 0 NOT NULL,
  refunded_total numeric(14,2) DEFAULT 0 NOT NULL,
  outstanding_total numeric(14,2) GENERATED ALWAYS AS (GREATEST(((total - paid_total) + refunded_total), (0)::numeric)) STORED,
  snapshot jsonb NOT NULL,
  snapshot_hash text NOT NULL,
  issued_at timestamp with time zone,
  issued_by uuid,
  voided_at timestamp with time zone,
  voided_by uuid,
  void_reason text,
  supersedes_invoice_version_id uuid,
  superseded_by_invoice_version_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.invoices (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  work_order_id uuid,
  customer_id uuid,
  tech_id uuid,
  invoice_number text,
  status text DEFAULT 'draft'::text NOT NULL,
  subtotal numeric(12,2) DEFAULT 0 NOT NULL,
  parts_cost numeric(12,2) DEFAULT 0 NOT NULL,
  labor_cost numeric(12,2) DEFAULT 0 NOT NULL,
  discount_total numeric(12,2) DEFAULT 0 NOT NULL,
  tax_total numeric(12,2) DEFAULT 0 NOT NULL,
  total numeric(12,2) DEFAULT 0 NOT NULL,
  currency character(3) DEFAULT 'USD'::bpchar NOT NULL,
  issued_at timestamp with time zone,
  due_date date,
  paid_at timestamp with time zone,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  active_invoice_version_id uuid,
  paid_total numeric(14,2) DEFAULT 0 NOT NULL,
  refunded_total numeric(14,2) DEFAULT 0 NOT NULL,
  outstanding_total numeric(14,2) DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS public.maintenance_rules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  service_code text NOT NULL,
  make text,
  model text,
  year_from integer,
  year_to integer,
  engine_family text,
  distance_km_normal integer,
  distance_km_severe integer,
  time_months_normal integer,
  time_months_severe integer,
  first_due_km integer,
  first_due_months integer,
  is_critical boolean DEFAULT false NOT NULL
);
CREATE TABLE IF NOT EXISTS public.maintenance_services (
  code text NOT NULL,
  label text NOT NULL,
  default_job_type text DEFAULT 'maintenance'::text NOT NULL,
  default_labor_hours numeric,
  default_notes text,
  interval_km integer,
  interval_months integer
);
CREATE TABLE IF NOT EXISTS public.maintenance_suggestions (
  work_order_id uuid NOT NULL,
  vehicle_id uuid,
  mileage_km integer,
  status text DEFAULT 'pending'::text NOT NULL,
  suggestions jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.menu_item_suggestions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  title text NOT NULL,
  category text,
  price_suggestion numeric,
  labor_hours_suggestion numeric,
  confidence numeric DEFAULT 0 NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  inspection_template_suggestion_id uuid
);
CREATE TABLE IF NOT EXISTS public.menu_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  name text,
  complaint text,
  cause text,
  correction text,
  labor_time numeric,
  tools text,
  created_at timestamp with time zone DEFAULT now(),
  category text,
  total_price numeric,
  part_cost numeric,
  labor_hours numeric,
  description text,
  is_active boolean DEFAULT true,
  shop_id uuid,
  inspection_template_id uuid,
  vehicle_year integer,
  vehicle_make text,
  vehicle_model text,
  engine_type text,
  transmission_type text,
  drivetrain text,
  submodel text,
  source text,
  base_labor_hours numeric,
  base_price numeric,
  work_order_line_id uuid,
  service_key text,
  base_part_cost numeric,
  engine_code text,
  transmission_code text
);
CREATE TABLE IF NOT EXISTS public.menu_repair_item_parts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  menu_repair_item_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  part_name text NOT NULL,
  part_number text,
  supplier_part_number text,
  qty numeric DEFAULT 1 NOT NULL,
  fitment_notes text,
  part_role text,
  is_required boolean DEFAULT true NOT NULL,
  last_seen_supplier text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.menu_repair_item_pricing_parts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  pricing_snapshot_id uuid NOT NULL,
  menu_repair_item_part_id uuid,
  part_name text NOT NULL,
  quoted_part_number text,
  supplier_part_number text,
  qty numeric DEFAULT 1 NOT NULL,
  unit_cost numeric,
  unit_sell numeric,
  availability text,
  lead_time text,
  core_charge numeric,
  freight numeric,
  notes text,
  match_confidence numeric,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.menu_repair_item_pricing_snapshots (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  menu_repair_item_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  supplier_id uuid,
  supplier_name text,
  quote_source text DEFAULT 'manual_upload'::text NOT NULL,
  quote_reference text,
  quoted_at timestamp with time zone DEFAULT now() NOT NULL,
  valid_until timestamp with time zone,
  pricing_valid_days integer DEFAULT 30 NOT NULL,
  total_cost numeric,
  total_sell numeric,
  currency text DEFAULT 'CAD'::text NOT NULL,
  status text DEFAULT 'fresh'::text NOT NULL,
  import_batch_id uuid,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  source_quote_line_id uuid,
  source_work_order_line_id uuid
);
CREATE TABLE IF NOT EXISTS public.menu_repair_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  source_work_order_id uuid,
  source_work_order_line_id uuid,
  name text NOT NULL,
  complaint text,
  cause text,
  correction text,
  notes text,
  vehicle_year integer,
  vehicle_make text,
  vehicle_model text,
  engine text,
  drivetrain text,
  transmission text,
  fuel_type text,
  labor_hours numeric,
  labor_rate numeric,
  price_estimate numeric,
  parts jsonb DEFAULT '[]'::jsonb NOT NULL,
  tags text[] DEFAULT '{}'::text[] NOT NULL,
  template_key text NOT NULL,
  usage_count integer DEFAULT 1 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  pricing_valid_days integer DEFAULT 30,
  last_pricing_refresh_at timestamp with time zone,
  last_pricing_source text,
  pricing_status text DEFAULT 'fresh'::text,
  active_pricing_snapshot_id uuid,
  source_quote_line_id uuid
);
CREATE TABLE IF NOT EXISTS public.optimization_actions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  opportunity_id text NOT NULL,
  type text NOT NULL,
  action text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  slug text,
  owner_profile_id uuid,
  stripe_customer_id text,
  billing_email text,
  billing_status text,
  default_currency text DEFAULT 'usd'::text,
  metadata jsonb
);
CREATE TABLE IF NOT EXISTS public.parts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  description text,
  price numeric(10,2),
  cost numeric(10,2),
  part_number text,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  shop_id uuid,
  sku text,
  supplier text,
  warranty_months integer DEFAULT 0,
  default_cost numeric,
  default_price numeric,
  subcategory text,
  low_stock_threshold numeric,
  unit text,
  taxable boolean DEFAULT true,
  normalized_part_key text,
  source_intake_id uuid,
  external_id text,
  import_notes text,
  manufacturer text
);
CREATE TABLE IF NOT EXISTS public.payroll_timecards (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  shop_id uuid,
  clock_in timestamp with time zone NOT NULL,
  clock_out timestamp with time zone,
  hours_worked numeric(8,2),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.people_workforce_profiles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  workforce_role text,
  workforce_category text,
  employment_status text DEFAULT 'active'::text NOT NULL,
  start_date date,
  payroll_ready boolean DEFAULT false NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.planner_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  step integer NOT NULL,
  kind text NOT NULL,
  content jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.planner_runs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL,
  planner_kind text NOT NULL,
  goal text NOT NULL,
  context jsonb DEFAULT '{}'::jsonb NOT NULL,
  idempotency_key text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  full_name text,
  email text,
  phone text,
  role text,
  shop_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  plan plan_t,
  business_name text,
  shop_name text,
  street text,
  city text,
  province text,
  postal_code text,
  created_by uuid,
  updated_at timestamp with time zone,
  completed_onboarding boolean DEFAULT false NOT NULL,
  last_active_at timestamp with time zone,
  user_id uuid,
  username text,
  must_change_password boolean DEFAULT false NOT NULL,
  agent_role text DEFAULT 'none'::text,
  organization_id uuid,
  tech_signature_path text,
  tech_signature_hash text,
  tech_signature_updated_at timestamp with time zone,
  avatar_url text,
  stripe_checkout_complete boolean DEFAULT false NOT NULL,
  stripe_checkout_session_id text,
  stripe_customer_id text,
  stripe_subscription_id text
);
CREATE TABLE IF NOT EXISTS public.property_assets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  property_id uuid NOT NULL,
  unit_id uuid,
  name text NOT NULL,
  asset_type text,
  manufacturer text,
  model text,
  serial_number text,
  install_date date,
  warranty_expires_on date,
  location_note text,
  status text DEFAULT 'active'::text NOT NULL,
  next_service_date date,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_inspection_signatures (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  inspection_id uuid NOT NULL,
  signer_profile_id uuid,
  signer_name text NOT NULL,
  signer_email text,
  signer_role text NOT NULL,
  signature_type text DEFAULT 'typed'::text NOT NULL,
  signature_text text,
  signature_image_path text,
  signed_at timestamp with time zone DEFAULT now() NOT NULL,
  ip_address inet,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_inspections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  property_id uuid NOT NULL,
  unit_id uuid,
  performed_by_profile_id uuid,
  inspection_type text DEFAULT 'general'::text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  summary text,
  findings jsonb DEFAULT '[]'::jsonb NOT NULL,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_maintenance_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  property_id uuid NOT NULL,
  unit_id uuid,
  asset_id uuid,
  requester_profile_id uuid,
  title text NOT NULL,
  summary text NOT NULL,
  category text,
  severity text DEFAULT 'routine'::text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  source text DEFAULT 'manual'::text NOT NULL,
  access_notes text,
  preferred_window text,
  photos jsonb DEFAULT '[]'::jsonb NOT NULL,
  ai_triage jsonb DEFAULT '{}'::jsonb NOT NULL,
  work_order_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_members (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  portfolio_id uuid,
  property_id uuid,
  unit_id uuid,
  role text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_portal_invites (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  invited_email text NOT NULL,
  invited_name text,
  role text DEFAULT 'tenant_requester'::text NOT NULL,
  portfolio_id uuid,
  property_id uuid,
  unit_id uuid,
  token_hash text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  accepted_by_profile_id uuid,
  accepted_at timestamp with time zone,
  created_by_profile_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_portfolios (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_properties (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  portfolio_id uuid,
  name text NOT NULL,
  property_type text,
  address_line1 text,
  address_line2 text,
  city text,
  region text,
  postal_code text,
  country text DEFAULT 'CA'::text,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_request_attachments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  request_id uuid NOT NULL,
  event_id uuid,
  uploaded_by_profile_id uuid,
  file_kind text DEFAULT 'image'::text NOT NULL,
  storage_bucket text,
  storage_path text,
  original_filename text,
  content_type text,
  size_bytes bigint,
  caption text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_request_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  request_id uuid NOT NULL,
  actor_profile_id uuid,
  actor_type text DEFAULT 'internal'::text NOT NULL,
  event_type text NOT NULL,
  visibility text DEFAULT 'internal'::text NOT NULL,
  body text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_units (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  property_id uuid NOT NULL,
  unit_label text NOT NULL,
  unit_type text,
  occupancy_status text,
  access_notes text,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_vendor_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  request_id uuid,
  work_order_id uuid,
  vendor_id uuid NOT NULL,
  status text DEFAULT 'assigned'::text NOT NULL,
  scheduled_for timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.property_vendors (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  name text NOT NULL,
  trade text,
  contact_name text,
  email text,
  phone text,
  status text DEFAULT 'active'::text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.quickbooks_connections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  created_by uuid,
  realm_id text NOT NULL,
  environment text DEFAULT 'production'::text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  access_token_expires_at timestamp with time zone NOT NULL,
  refresh_token_expires_at timestamp with time zone,
  token_scope text[] DEFAULT '{}'::text[] NOT NULL,
  token_type text,
  connected_at timestamp with time zone DEFAULT now() NOT NULL,
  last_sync_at timestamp with time zone,
  last_error text,
  is_active boolean DEFAULT true NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.quickbooks_customer_links (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  qb_customer_id text NOT NULL,
  qb_sync_token text,
  sync_status text DEFAULT 'synced'::text NOT NULL,
  last_synced_at timestamp with time zone,
  last_error text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.quickbooks_sync_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  connection_id uuid,
  entity_type text NOT NULL,
  entity_id uuid,
  action text NOT NULL,
  status text NOT NULL,
  request_payload jsonb,
  response_payload jsonb,
  error_message text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_ai_profiles (
  shop_id uuid NOT NULL,
  summary jsonb NOT NULL,
  last_refreshed_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_boost_import_provenance (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  domain text NOT NULL,
  record_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_boost_import_reset_audit_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  actor_user_id uuid NOT NULL,
  scope text NOT NULL,
  mode text NOT NULL,
  confirmation_text text NOT NULL,
  preview_counts jsonb DEFAULT '{}'::jsonb NOT NULL,
  deleted_counts jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_boost_intakes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  questionnaire jsonb NOT NULL,
  customers_file_path text,
  vehicles_file_path text,
  parts_file_path text,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  processed_at timestamp with time zone,
  source text,
  intake_basics jsonb,
  created_by uuid,
  staff_file_path text,
  history_file_path text,
  source_system_guess text,
  upload_status text,
  import_counts jsonb DEFAULT '{}'::jsonb,
  parse_summary jsonb DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS public.shop_boost_integrity_reports (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  status text NOT NULL,
  graph_ready boolean DEFAULT false NOT NULL,
  blocking_issues_count integer DEFAULT 0 NOT NULL,
  warnings_count integer DEFAULT 0 NOT NULL,
  checks jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_boost_review_audit_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  review_item_id uuid NOT NULL,
  actor_user_id uuid,
  event_type text NOT NULL,
  recommendation jsonb DEFAULT '{}'::jsonb NOT NULL,
  action_taken text,
  followed_recommendation boolean,
  materialization_status text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_boost_review_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  domain text NOT NULL,
  issue_type text NOT NULL,
  summary text NOT NULL,
  raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  suggested_matches jsonb DEFAULT '[]'::jsonb NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  resolution_action text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  materialized_at timestamp with time zone,
  materialization_error text,
  materialized_record jsonb DEFAULT '{}'::jsonb NOT NULL,
  normalized_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  target_domain text,
  blocking_reason text,
  dependency_refs jsonb DEFAULT '{}'::jsonb NOT NULL,
  downstream_impact_count integer DEFAULT 0 NOT NULL,
  cluster_key text,
  cluster_confidence numeric(5,4) DEFAULT 0,
  ignore_reason_code text,
  ignore_note text,
  ignored_at timestamp with time zone,
  recommended_action text,
  recommendation_reason text,
  recommendation_confidence numeric(5,4),
  candidate_targets jsonb DEFAULT '[]'::jsonb NOT NULL,
  recommendation_generated_at timestamp with time zone,
  recommendation_seen_at timestamp with time zone,
  recommendation_followed boolean
);
CREATE TABLE IF NOT EXISTS public.shop_boost_row_results (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  source_file text NOT NULL,
  source_row_index integer NOT NULL,
  raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  normalized_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  target_domain text NOT NULL,
  match_status text NOT NULL,
  match_confidence numeric(5,4) DEFAULT 0 NOT NULL,
  match_details jsonb DEFAULT '{}'::jsonb NOT NULL,
  error_reason text,
  review_required boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  cluster_key text,
  cluster_confidence numeric(5,4) DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.shop_brand_assets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  kind brand_asset_kind NOT NULL,
  file_url text,
  storage_bucket text,
  storage_path text,
  source_app brand_source_app DEFAULT 'profixiq'::brand_source_app NOT NULL,
  generation_provider text,
  generation_prompt text,
  mime_type text,
  file_name text,
  file_size_bytes bigint,
  width integer,
  height integer,
  is_active boolean DEFAULT false NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  is_favorite boolean DEFAULT false NOT NULL,
  archived_at timestamp with time zone,
  archived_by uuid
);
CREATE TABLE IF NOT EXISTS public.shop_brand_profiles (
  shop_id uuid NOT NULL,
  primary_color text,
  secondary_color text,
  accent_color text,
  style_preset text,
  logo_asset_id uuid,
  icon_asset_id uuid,
  wordmark_asset_id uuid,
  watermark_asset_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  surface_color text,
  surface_color_2 text,
  sidebar_color text,
  topbar_color text,
  page_background text,
  card_background text,
  card_border_color text,
  text_primary text,
  text_secondary text,
  button_primary_bg text,
  button_primary_text text,
  button_secondary_bg text,
  button_secondary_text text,
  input_background text,
  input_border text,
  input_text text,
  radius_scale text,
  shadow_style text,
  theme_mode text,
  app_background text,
  app_background_secondary text,
  sidebar_background text,
  sidebar_text text,
  sidebar_active_background text,
  sidebar_active_text text,
  header_background text,
  header_text text,
  card_border text,
  surface_2_background text,
  text_muted text
);
CREATE TABLE IF NOT EXISTS public.shop_health_snapshots (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  period_start date,
  period_end date,
  metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  scores jsonb DEFAULT '{}'::jsonb NOT NULL,
  narrative_summary text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_import_files (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  intake_id uuid NOT NULL,
  kind text NOT NULL,
  storage_path text NOT NULL,
  original_filename text,
  sha256 text,
  parsed_row_count integer,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_import_rows (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  intake_id uuid NOT NULL,
  file_id uuid,
  row_number integer,
  entity_type text,
  raw jsonb DEFAULT '{}'::jsonb NOT NULL,
  normalized jsonb DEFAULT '{}'::jsonb NOT NULL,
  errors text[] DEFAULT '{}'::text[] NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  shop_id uuid,
  original_headers jsonb DEFAULT '[]'::jsonb,
  raw_payload jsonb DEFAULT '{}'::jsonb,
  parse_status text DEFAULT 'pending'::text,
  parse_warnings jsonb DEFAULT '[]'::jsonb
);
CREATE TABLE IF NOT EXISTS public.shop_maintenance_service_map (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  service_code text NOT NULL,
  menu_item_id uuid,
  menu_repair_item_id uuid,
  label_override text,
  is_active boolean DEFAULT true NOT NULL,
  match_source text DEFAULT 'manual'::text NOT NULL,
  confidence numeric(5,4),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_members (
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid
);
CREATE TABLE IF NOT EXISTS public.shop_onboarding_activation_rules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  min_customer_rows integer DEFAULT 1 NOT NULL,
  min_vehicle_rows integer DEFAULT 1 NOT NULL,
  max_pending_review_ratio numeric(5,4) DEFAULT 0.08 NOT NULL,
  max_failed_ratio numeric(5,4) DEFAULT 0.02 NOT NULL,
  require_zero_integrity_errors boolean DEFAULT true NOT NULL,
  require_canonical_status_ok boolean DEFAULT true NOT NULL,
  auto_activate boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_onboarding_attempts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  run_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  completed_at timestamp with time zone,
  worker_id text,
  status text DEFAULT 'running'::text NOT NULL,
  error_code text,
  error_message text,
  logs jsonb DEFAULT '[]'::jsonb NOT NULL,
  metrics jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_onboarding_jobs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  job_type text NOT NULL,
  domain text,
  status text DEFAULT 'queued'::text NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  depends_on_job_id uuid,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  result jsonb DEFAULT '{}'::jsonb NOT NULL,
  error_code text,
  error_message text,
  retry_after timestamp with time zone,
  attempt_count integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 8 NOT NULL,
  idempotency_key text NOT NULL,
  locked_by text,
  locked_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_onboarding_runs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid NOT NULL,
  orchestrator_version text DEFAULT 'v1'::text NOT NULL,
  state text DEFAULT 'uploaded'::text NOT NULL,
  trigger_source text DEFAULT 'manual'::text NOT NULL,
  lock_token uuid,
  locked_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  error_code text,
  error_message text,
  retry_after timestamp with time zone,
  max_attempts integer DEFAULT 12 NOT NULL,
  attempt_count integer DEFAULT 0 NOT NULL,
  activation_status text DEFAULT 'not_eligible'::text NOT NULL,
  activation_blockers jsonb DEFAULT '[]'::jsonb NOT NULL,
  activation_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
  metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_parts_import_match_candidates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  staging_row_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  candidate_part_id uuid,
  confidence numeric(5,4) NOT NULL,
  reason text,
  rank integer DEFAULT 1 NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_parts_import_staging (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  intake_id uuid NOT NULL,
  raw_row_id uuid,
  shop_id uuid NOT NULL,
  source_system text,
  normalized_name text,
  normalized_name_key text,
  normalized_sku text,
  normalized_part_number text,
  normalized_brand text,
  normalized_vendor text,
  mapped_category text,
  quantity_on_hand numeric(12,2),
  cost numeric(12,2),
  price numeric(12,2),
  unit_of_measure text,
  pack_info text,
  source_confidence numeric(5,4),
  status text DEFAULT 'pending'::text NOT NULL,
  warnings jsonb DEFAULT '[]'::jsonb NOT NULL,
  raw_echo jsonb DEFAULT '{}'::jsonb NOT NULL,
  suggested_action text,
  matched_part_id uuid,
  match_reason text,
  auto_promote boolean DEFAULT false NOT NULL,
  promoted_at timestamp with time zone,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_parts_source_aliases (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  raw_row_id uuid,
  staging_row_id uuid,
  part_id uuid NOT NULL,
  source_system text,
  legacy_sku text,
  legacy_part_number text,
  legacy_label text,
  vendor_alias text,
  alias_type text DEFAULT 'legacy_import'::text NOT NULL,
  source_hash text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shop_vehicle_menu_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_menu_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_drafts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  opportunity_id uuid NOT NULL,
  status shopreel_draft_status DEFAULT 'draft'::shopreel_draft_status NOT NULL,
  title text NOT NULL,
  angle text,
  script text,
  created_by uuid,
  updated_by uuid,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_event_deliveries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  integration_id uuid,
  event_key text NOT NULL,
  event_type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  request_url text NOT NULL,
  http_status integer,
  status text DEFAULT 'pending'::text NOT NULL,
  attempt_count integer DEFAULT 0 NOT NULL,
  response_body text,
  error_message text,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_integrations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  shopreel_base_url text DEFAULT 'https://shopreel.profixiq.com'::text NOT NULL,
  remote_shop_id uuid,
  enabled_event_types text[] DEFAULT ARRAY['inspection.completed'::text, 'inspection.finding.flagged'::text, 'inspection.media.captured'::text, 'workorder.approved'::text, 'workorder.completed'::text, 'media.before_after.added'::text] NOT NULL,
  last_tested_at timestamp with time zone,
  last_success_at timestamp with time zone,
  last_error_at timestamp with time zone,
  last_error_message text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by uuid,
  updated_by uuid
);
CREATE TABLE IF NOT EXISTS public.shopreel_manual_assets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  created_by uuid,
  title text NOT NULL,
  description text,
  source_type text DEFAULT 'manual_upload'::text NOT NULL,
  asset_type text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  content_goal text,
  note text,
  platform_targets text[] DEFAULT '{}'::text[] NOT NULL,
  tags text[] DEFAULT '{}'::text[] NOT NULL,
  primary_file_url text,
  thumbnail_url text,
  duration_seconds numeric,
  metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_opportunities (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  story_source_id uuid NOT NULL,
  status shopreel_opportunity_status DEFAULT 'new'::shopreel_opportunity_status NOT NULL,
  title text NOT NULL,
  angle text,
  summary text,
  event_type text NOT NULL,
  source_occurred_at timestamp with time zone NOT NULL,
  first_generated_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  accepted_at timestamp with time zone,
  generated_at timestamp with time zone,
  acted_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_opportunity_status_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  opportunity_id uuid NOT NULL,
  previous_status shopreel_opportunity_status,
  next_status shopreel_opportunity_status NOT NULL,
  action shopreel_opportunity_action,
  note text,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_publications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  video_id uuid,
  connection_id uuid,
  platform text NOT NULL,
  status text DEFAULT 'queued'::text NOT NULL,
  scheduled_for timestamp with time zone,
  published_at timestamp with time zone,
  external_post_id text,
  external_url text,
  caption_override text,
  title_override text,
  publish_payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  response_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  error_message text,
  attempt_count integer DEFAULT 0 NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_publish_jobs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  publication_id uuid NOT NULL,
  status text DEFAULT 'queued'::text NOT NULL,
  run_after timestamp with time zone DEFAULT now() NOT NULL,
  locked_at timestamp with time zone,
  locked_by text,
  completed_at timestamp with time zone,
  error_message text,
  attempt_count integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_social_connections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  platform text NOT NULL,
  account_id text,
  account_name text,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  connection_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  meta_page_id text,
  meta_page_name text,
  meta_instagram_business_id text,
  scopes text[] DEFAULT '{}'::text[] NOT NULL,
  metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shopreel_story_sources (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  event_key text NOT NULL,
  event_type text NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  ingest_status text DEFAULT 'ingested'::text NOT NULL,
  ingested_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.shops (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  owner_id uuid,
  business_name text,
  plan text,
  user_limit integer DEFAULT 1,
  active_user_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  address text,
  postal_code text,
  city text,
  province text,
  phone_number text,
  email text,
  logo_url text,
  labor_rate numeric,
  supplies_percent numeric,
  diagnostic_fee numeric,
  tax_rate numeric,
  use_ai boolean DEFAULT false,
  require_cause_correction boolean DEFAULT false,
  require_authorization boolean DEFAULT false,
  invoice_terms text,
  invoice_footer text,
  email_on_complete boolean DEFAULT false,
  auto_generate_pdf boolean DEFAULT false,
  auto_send_quote_email boolean DEFAULT false,
  slug text,
  timezone text DEFAULT 'America/Los_Angeles'::text,
  accepts_online_booking boolean DEFAULT true,
  min_notice_minutes integer DEFAULT 120,
  max_lead_days integer DEFAULT 30,
  owner_pin_hash text,
  name text,
  pin text,
  shop_name text,
  street text,
  owner_pin text,
  created_by uuid,
  updated_at timestamp with time zone,
  geo_lat numeric,
  geo_lng numeric,
  images text[] DEFAULT '{}'::text[],
  rating numeric,
  country text DEFAULT 'US'::text,
  max_users integer GENERATED ALWAYS AS (
CASE plan
    WHEN 'pro'::text THEN 30
    WHEN 'pro_plus'::text THEN 2147483647
    ELSE COALESCE(user_limit, 1)
END) STORED,
  stripe_account_id text,
  stripe_charges_enabled boolean DEFAULT false NOT NULL,
  stripe_payouts_enabled boolean DEFAULT false NOT NULL,
  stripe_details_submitted boolean DEFAULT false NOT NULL,
  stripe_onboarding_completed boolean DEFAULT false NOT NULL,
  stripe_default_currency text DEFAULT 'usd'::text NOT NULL,
  stripe_platform_fee_bps integer DEFAULT 0 NOT NULL,
  stripe_subscription_status text,
  stripe_trial_end timestamp with time zone,
  stripe_current_period_end timestamp with time zone,
  stripe_subscription_id text,
  stripe_customer_id text,
  organization_id uuid,
  default_stock_location_id uuid,
  menu_repair_pricing_valid_days integer DEFAULT 30 NOT NULL,
  shop_supplies_enabled boolean DEFAULT false,
  shop_supplies_type text DEFAULT 'percentage'::text,
  shop_supplies_percent numeric,
  shop_supplies_flat_amount numeric,
  shop_supplies_cap_amount numeric,
  stripe_checkout_session_id text
);
CREATE TABLE IF NOT EXISTS public.staff_certifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  user_id uuid NOT NULL,
  cert_type text DEFAULT 'certification'::text NOT NULL,
  cert_name text NOT NULL,
  cert_number text,
  issuing_body text,
  issue_date date,
  expiry_date date,
  status text DEFAULT 'active'::text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.staff_invite_candidates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  full_name text,
  email text,
  phone text,
  username text,
  role user_role_enum,
  source text DEFAULT 'staff_csv'::text NOT NULL,
  confidence numeric,
  created_profile_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  email_lc text GENERATED ALWAYS AS (lower(email)) STORED,
  username_lc text GENERATED ALWAYS AS (lower(username)) STORED,
  status text DEFAULT 'pending'::text NOT NULL,
  created_user_id uuid,
  created_by uuid,
  error text
);
CREATE TABLE IF NOT EXISTS public.staff_invite_suggestions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  role text NOT NULL,
  count_suggested integer DEFAULT 0 NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  full_name text,
  email text,
  external_id text
);
CREATE TABLE IF NOT EXISTS public.stock_locations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.supplier_quote_batch_rows (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  batch_id uuid NOT NULL,
  raw_part_number text,
  raw_description text,
  raw_qty numeric,
  raw_unit_cost numeric,
  raw_sell numeric,
  raw_notes text,
  mapped_menu_repair_item_id uuid,
  mapped_menu_repair_item_part_id uuid,
  mapped_confidence numeric,
  review_status text DEFAULT 'unmatched'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.supplier_quote_batches (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  supplier_id uuid,
  supplier_name text,
  source_type text DEFAULT 'csv_upload'::text NOT NULL,
  file_name text,
  storage_path text,
  status text DEFAULT 'uploaded'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  processed_at timestamp with time zone,
  uploaded_by uuid
);
CREATE TABLE IF NOT EXISTS public.suppliers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  account_no text,
  notes text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid DEFAULT auth.uid()
);
CREATE TABLE IF NOT EXISTS public.user_theme_preferences (
  user_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  theme_mode text,
  radius_scale text,
  shadow_style text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.vehicle_menus (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  make text NOT NULL,
  model text NOT NULL,
  year_from integer NOT NULL,
  year_to integer NOT NULL,
  engine_family text,
  service_code text NOT NULL,
  default_labor_hours numeric,
  default_parts jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.vehicles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  year integer,
  make text,
  model text,
  vin text,
  created_at timestamp with time zone DEFAULT now(),
  license_plate text,
  mileage text,
  color text,
  customer_id uuid,
  shop_id uuid,
  unit_number text,
  engine_hours integer,
  engine_type text,
  transmission_type text,
  drivetrain text,
  submodel text,
  engine text,
  transmission text,
  fuel_type text,
  engine_family text,
  source_intake_id uuid,
  source_row_id uuid,
  external_id text,
  import_confidence numeric,
  import_notes text,
  state_province text,
  odometer_unit text,
  body_type text,
  asset_type text,
  status text,
  purchase_date date,
  in_service_date date,
  last_service_date date,
  tags text,
  notes text
);
CREATE TABLE IF NOT EXISTS public.videos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  template_id uuid,
  source_asset_id uuid,
  title text NOT NULL,
  slug text,
  status text DEFAULT 'draft'::text NOT NULL,
  content_type text NOT NULL,
  hook text,
  caption text,
  cta text,
  script_text text,
  voiceover_text text,
  platform_targets text[] DEFAULT '{}'::text[] NOT NULL,
  published_at timestamp with time zone,
  thumbnail_url text,
  render_url text,
  duration_seconds numeric(10,2),
  generation_notes text,
  ai_score numeric(6,2),
  human_rating integer,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.work_order_invoice_reviews (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  work_order_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  created_by uuid DEFAULT auth.uid(),
  ok boolean DEFAULT false NOT NULL,
  issues jsonb DEFAULT '[]'::jsonb NOT NULL,
  model text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.work_order_line_ai (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  intake_id uuid,
  work_order_id uuid NOT NULL,
  work_order_line_id uuid NOT NULL,
  primary_category text,
  secondary_categories text[] DEFAULT '{}'::text[] NOT NULL,
  job_scope text,
  confidence numeric DEFAULT 0 NOT NULL,
  signals text[] DEFAULT '{}'::text[] NOT NULL,
  summary text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.work_order_line_dtc_threads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  work_order_line_id uuid NOT NULL,
  work_order_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  vehicle_id uuid,
  created_by uuid,
  dtc_code text,
  messages jsonb DEFAULT '[]'::jsonb NOT NULL,
  summary jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid
);
CREATE TABLE IF NOT EXISTS public.work_order_lines (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  work_order_id uuid NOT NULL,
  complaint text,
  cause text,
  correction text,
  tools text,
  labor_time numeric,
  created_at timestamp with time zone DEFAULT now(),
  line_status text,
  parts_required jsonb DEFAULT '[]'::jsonb,
  parts_received jsonb DEFAULT '[]'::jsonb,
  on_hold_since timestamp without time zone,
  hold_reason text,
  description text,
  user_id uuid,
  vehicle_id uuid,
  assigned_to uuid,
  job_type text DEFAULT 'repair'::text,
  priority smallint DEFAULT 100,
  status text DEFAULT 'awaiting'::text NOT NULL,
  punched_in_at timestamp with time zone,
  punched_out_at timestamp with time zone,
  assigned_tech_id uuid,
  updated_at timestamp with time zone,
  parts_needed jsonb,
  template_id uuid,
  notes text,
  shop_id uuid NOT NULL,
  approval_state text,
  approval_at timestamp with time zone,
  approval_by uuid,
  approval_note text,
  inspection_session_id uuid,
  urgency text DEFAULT 'medium'::text,
  parts text,
  price_estimate numeric,
  quoted_at timestamp with time zone,
  line_no integer,
  punchable boolean GENERATED ALWAYS AS (((approval_state = 'approved'::text) AND (status <> ALL (ARRAY['awaiting_approval'::text, 'declined'::text])))) STORED,
  inspection_template_id uuid,
  menu_item_id uuid,
  service_code text,
  odometer_km integer,
  source_intake_id uuid,
  source_row_id uuid,
  external_id text,
  import_confidence numeric,
  import_notes text,
  voided_at timestamp with time zone,
  voided_reason text,
  voided_note text,
  voided_by uuid,
  intake_json jsonb,
  intake_status text,
  intake_submitted_at timestamp with time zone,
  intake_submitted_by uuid,
  line_type text DEFAULT 'job'::text NOT NULL,
  job_priority text DEFAULT 'normal'::text,
  source_inspection_id uuid,
  source_inspection_item_key text
);
CREATE TABLE IF NOT EXISTS public.work_orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  vehicle_id uuid,
  inspection_id uuid,
  customer_id uuid,
  assigned_tech uuid,
  status text DEFAULT 'awaiting_approval'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  labor_total numeric,
  parts_total numeric,
  invoice_total numeric,
  quote jsonb,
  customer_name text,
  vehicle_info text,
  inspection_type text,
  inspection_pdf_url text,
  shop_id uuid NOT NULL,
  quote_url text,
  notes text,
  type text,
  custom_id text,
  updated_at timestamp with time zone DEFAULT now(),
  invoice_url text,
  approval_state text,
  vehicle_unit_number text,
  vehicle_color text,
  vehicle_mileage integer,
  vehicle_engine_hours integer,
  customer_approval_signature_url text,
  customer_approval_at timestamp with time zone,
  customer_approval_signature_path text,
  customer_approved_by uuid,
  created_by uuid,
  priority integer DEFAULT 3,
  odometer_km integer,
  is_waiter boolean DEFAULT false NOT NULL,
  invoice_sent_at timestamp with time zone,
  invoice_last_sent_to text,
  invoice_pdf_url text,
  source_fleet_service_request_id uuid,
  source_fleet_program_id uuid,
  source_intake_id uuid,
  source_row_id uuid,
  external_id text,
  import_confidence numeric,
  import_notes text,
  vehicle_vin text,
  vehicle_license_plate text,
  vehicle_make text,
  vehicle_model text,
  vehicle_year integer,
  vehicle_submodel text,
  vehicle_engine text,
  vehicle_drivetrain text,
  vehicle_fuel_type text,
  vehicle_transmission text,
  intake_json jsonb,
  intake_status text DEFAULT 'draft'::text,
  intake_submitted_at timestamp with time zone,
  intake_submitted_by uuid,
  customer_agreed_at timestamp with time zone,
  customer_signature_url text,
  portal_submitted_at timestamp with time zone,
  advisor_id uuid,
  scheduled_at timestamp with time zone,
  expected_completion_at timestamp with time zone,
  shop_supplies_enabled_override boolean,
  shop_supplies_amount_override numeric,
  payment_status text DEFAULT 'unpaid'::text NOT NULL,
  outstanding_balance numeric(14,2) DEFAULT 0 NOT NULL,
  paid_at timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public.workforce_document_requirements (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  shop_id uuid NOT NULL,
  workforce_role text,
  workforce_category text,
  doc_type text NOT NULL,
  label text NOT NULL,
  is_required boolean DEFAULT true NOT NULL,
  expires_required boolean DEFAULT false NOT NULL,
  expires_warning_days integer DEFAULT 30 NOT NULL,
  accept_statuses text[] DEFAULT ARRAY['active'::text, 'approved'::text, 'accepted'::text] NOT NULL,
  review_statuses text[] DEFAULT ARRAY['received'::text, 'pending'::text, 'review'::text, 'needs_review'::text] NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  updated_by uuid
);

COMMIT;
