-- P0-008: add live runtime columns to relations that predate the recovery snapshot.
-- CREATE TABLE IF NOT EXISTS cannot repair the shape of an existing relation, so
-- this layer makes every recovered live column idempotently available before
-- constraints, functions, views, triggers, and authorization are restored.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '15min';

ALTER TABLE public.agent_runs
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS status text NOT NULL,
  ADD COLUMN IF NOT EXISTS goal text NOT NULL,
  ADD COLUMN IF NOT EXISTS idempotency_key text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS phone_number text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS province text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS shop_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle text,
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS is_fleet boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS source_intake_id uuid,
  ADD COLUMN IF NOT EXISTS source_row_id uuid,
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS import_confidence numeric,
  ADD COLUMN IF NOT EXISTS import_notes text,
  ADD COLUMN IF NOT EXISTS customer_since timestamp with time zone;

ALTER TABLE public.fleets
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS name text NOT NULL,
  ADD COLUMN IF NOT EXISTS contact_name text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;

ALTER TABLE public.inspection_sessions
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS work_order_id uuid,
  ADD COLUMN IF NOT EXISTS state jsonb,
  ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS work_order_line_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle_id uuid,
  ADD COLUMN IF NOT EXISTS customer_id uuid,
  ADD COLUMN IF NOT EXISTS template text,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'new'::text NOT NULL;

ALTER TABLE public.inspection_templates
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS template_name text NOT NULL,
  ADD COLUMN IF NOT EXISTS sections jsonb NOT NULL,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS tags text[],
  ADD COLUMN IF NOT EXISTS vehicle_type text,
  ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS labor_hours numeric(5,2),
  ADD COLUMN IF NOT EXISTS shop_id uuid;

ALTER TABLE public.inspections
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle_id uuid,
  ADD COLUMN IF NOT EXISTS template_id uuid,
  ADD COLUMN IF NOT EXISTS inspection_type text,
  ADD COLUMN IF NOT EXISTS completed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'not_started'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS started_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS summary jsonb,
  ADD COLUMN IF NOT EXISTS photo_urls text[],
  ADD COLUMN IF NOT EXISTS pdf_url text,
  ADD COLUMN IF NOT EXISTS quote_id uuid,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS ai_summary text,
  ADD COLUMN IF NOT EXISTS is_draft boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS work_order_id uuid,
  ADD COLUMN IF NOT EXISTS finalized_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS finalized_by uuid,
  ADD COLUMN IF NOT EXISTS locked boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS pdf_storage_path text,
  ADD COLUMN IF NOT EXISTS work_order_line_id uuid,
  ADD COLUMN IF NOT EXISTS signing_cycle bigint DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS reopened_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS reopened_by uuid,
  ADD COLUMN IF NOT EXISTS reopen_reason text,
  ADD COLUMN IF NOT EXISTS is_canonical boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS sync_revision bigint DEFAULT 0 NOT NULL;

ALTER TABLE public.invoice_versions
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS work_order_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS invoice_id uuid,
  ADD COLUMN IF NOT EXISTS version_number integer NOT NULL,
  ADD COLUMN IF NOT EXISTS lifecycle_status text DEFAULT 'issued'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS currency text NOT NULL,
  ADD COLUMN IF NOT EXISTS subtotal numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS discount_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS tax_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS paid_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS refunded_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS outstanding_total numeric(14,2) GENERATED ALWAYS AS (GREATEST(((total - paid_total) + refunded_total), (0)::numeric)) STORED,
  ADD COLUMN IF NOT EXISTS snapshot jsonb NOT NULL,
  ADD COLUMN IF NOT EXISTS snapshot_hash text NOT NULL,
  ADD COLUMN IF NOT EXISTS issued_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS issued_by uuid,
  ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS voided_by uuid,
  ADD COLUMN IF NOT EXISTS void_reason text,
  ADD COLUMN IF NOT EXISTS supersedes_invoice_version_id uuid,
  ADD COLUMN IF NOT EXISTS superseded_by_invoice_version_id uuid,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS work_order_id uuid,
  ADD COLUMN IF NOT EXISTS customer_id uuid,
  ADD COLUMN IF NOT EXISTS tech_id uuid,
  ADD COLUMN IF NOT EXISTS invoice_number text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS subtotal numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS parts_cost numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS labor_cost numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS discount_total numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS tax_total numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS total numeric(12,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS currency character(3) DEFAULT 'USD'::bpchar NOT NULL,
  ADD COLUMN IF NOT EXISTS issued_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS due_date date,
  ADD COLUMN IF NOT EXISTS paid_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS active_invoice_version_id uuid,
  ADD COLUMN IF NOT EXISTS paid_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS refunded_total numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS outstanding_total numeric(14,2) DEFAULT 0 NOT NULL;

ALTER TABLE public.menu_items
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS complaint text,
  ADD COLUMN IF NOT EXISTS cause text,
  ADD COLUMN IF NOT EXISTS correction text,
  ADD COLUMN IF NOT EXISTS labor_time numeric,
  ADD COLUMN IF NOT EXISTS tools text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS total_price numeric,
  ADD COLUMN IF NOT EXISTS part_cost numeric,
  ADD COLUMN IF NOT EXISTS labor_hours numeric,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS shop_id uuid,
  ADD COLUMN IF NOT EXISTS inspection_template_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle_year integer,
  ADD COLUMN IF NOT EXISTS vehicle_make text,
  ADD COLUMN IF NOT EXISTS vehicle_model text,
  ADD COLUMN IF NOT EXISTS engine_type text,
  ADD COLUMN IF NOT EXISTS transmission_type text,
  ADD COLUMN IF NOT EXISTS drivetrain text,
  ADD COLUMN IF NOT EXISTS submodel text,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS base_labor_hours numeric,
  ADD COLUMN IF NOT EXISTS base_price numeric,
  ADD COLUMN IF NOT EXISTS work_order_line_id uuid,
  ADD COLUMN IF NOT EXISTS service_key text,
  ADD COLUMN IF NOT EXISTS base_part_cost numeric,
  ADD COLUMN IF NOT EXISTS engine_code text,
  ADD COLUMN IF NOT EXISTS transmission_code text;

ALTER TABLE public.parts
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS name text NOT NULL,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS price numeric(10,2),
  ADD COLUMN IF NOT EXISTS cost numeric(10,2),
  ADD COLUMN IF NOT EXISTS part_number text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS shop_id uuid,
  ADD COLUMN IF NOT EXISTS sku text,
  ADD COLUMN IF NOT EXISTS supplier text,
  ADD COLUMN IF NOT EXISTS warranty_months integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS default_cost numeric,
  ADD COLUMN IF NOT EXISTS default_price numeric,
  ADD COLUMN IF NOT EXISTS subcategory text,
  ADD COLUMN IF NOT EXISTS low_stock_threshold numeric,
  ADD COLUMN IF NOT EXISTS unit text,
  ADD COLUMN IF NOT EXISTS taxable boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS normalized_part_key text,
  ADD COLUMN IF NOT EXISTS source_intake_id uuid,
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS import_notes text,
  ADD COLUMN IF NOT EXISTS manufacturer text;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS role text,
  ADD COLUMN IF NOT EXISTS shop_id uuid,
  ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS plan plan_t,
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS shop_name text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS province text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS completed_onboarding boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS last_active_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS username text,
  ADD COLUMN IF NOT EXISTS must_change_password boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS agent_role text DEFAULT 'none'::text,
  ADD COLUMN IF NOT EXISTS organization_id uuid,
  ADD COLUMN IF NOT EXISTS tech_signature_path text,
  ADD COLUMN IF NOT EXISTS tech_signature_hash text,
  ADD COLUMN IF NOT EXISTS tech_signature_updated_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS stripe_checkout_complete boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id text,
  ADD COLUMN IF NOT EXISTS stripe_customer_id text,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id text;

ALTER TABLE public.shops
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS owner_id uuid,
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS plan text,
  ADD COLUMN IF NOT EXISTS user_limit integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS active_user_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS province text,
  ADD COLUMN IF NOT EXISTS phone_number text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS logo_url text,
  ADD COLUMN IF NOT EXISTS labor_rate numeric,
  ADD COLUMN IF NOT EXISTS supplies_percent numeric,
  ADD COLUMN IF NOT EXISTS diagnostic_fee numeric,
  ADD COLUMN IF NOT EXISTS tax_rate numeric,
  ADD COLUMN IF NOT EXISTS use_ai boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS require_cause_correction boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS require_authorization boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS invoice_terms text,
  ADD COLUMN IF NOT EXISTS invoice_footer text,
  ADD COLUMN IF NOT EXISTS email_on_complete boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_generate_pdf boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_send_quote_email boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'America/Los_Angeles'::text,
  ADD COLUMN IF NOT EXISTS accepts_online_booking boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS min_notice_minutes integer DEFAULT 120,
  ADD COLUMN IF NOT EXISTS max_lead_days integer DEFAULT 30,
  ADD COLUMN IF NOT EXISTS owner_pin_hash text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS pin text,
  ADD COLUMN IF NOT EXISTS shop_name text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS owner_pin text,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS geo_lat numeric,
  ADD COLUMN IF NOT EXISTS geo_lng numeric,
  ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS rating numeric,
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'US'::text,
  ADD COLUMN IF NOT EXISTS max_users integer GENERATED ALWAYS AS (
    CASE plan
      WHEN 'pro'::text THEN 30
      WHEN 'pro_plus'::text THEN 2147483647
      ELSE COALESCE(user_limit, 1)
    END
  ) STORED,
  ADD COLUMN IF NOT EXISTS stripe_account_id text,
  ADD COLUMN IF NOT EXISTS stripe_charges_enabled boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_payouts_enabled boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_details_submitted boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_onboarding_completed boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_default_currency text DEFAULT 'usd'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_platform_fee_bps integer DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS stripe_subscription_status text,
  ADD COLUMN IF NOT EXISTS stripe_trial_end timestamp with time zone,
  ADD COLUMN IF NOT EXISTS stripe_current_period_end timestamp with time zone,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id text,
  ADD COLUMN IF NOT EXISTS stripe_customer_id text,
  ADD COLUMN IF NOT EXISTS organization_id uuid,
  ADD COLUMN IF NOT EXISTS default_stock_location_id uuid,
  ADD COLUMN IF NOT EXISTS menu_repair_pricing_valid_days integer DEFAULT 30 NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_supplies_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS shop_supplies_type text DEFAULT 'percentage'::text,
  ADD COLUMN IF NOT EXISTS shop_supplies_percent numeric,
  ADD COLUMN IF NOT EXISTS shop_supplies_flat_amount numeric,
  ADD COLUMN IF NOT EXISTS shop_supplies_cap_amount numeric,
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id text;

ALTER TABLE public.stock_locations
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS code text NOT NULL,
  ADD COLUMN IF NOT EXISTS name text NOT NULL;

ALTER TABLE public.suppliers
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS name text NOT NULL,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS account_no text,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS created_by uuid DEFAULT auth.uid();

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS year integer,
  ADD COLUMN IF NOT EXISTS make text,
  ADD COLUMN IF NOT EXISTS model text,
  ADD COLUMN IF NOT EXISTS vin text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS license_plate text,
  ADD COLUMN IF NOT EXISTS mileage text,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS customer_id uuid,
  ADD COLUMN IF NOT EXISTS shop_id uuid,
  ADD COLUMN IF NOT EXISTS unit_number text,
  ADD COLUMN IF NOT EXISTS engine_hours integer,
  ADD COLUMN IF NOT EXISTS engine_type text,
  ADD COLUMN IF NOT EXISTS transmission_type text,
  ADD COLUMN IF NOT EXISTS drivetrain text,
  ADD COLUMN IF NOT EXISTS submodel text,
  ADD COLUMN IF NOT EXISTS engine text,
  ADD COLUMN IF NOT EXISTS transmission text,
  ADD COLUMN IF NOT EXISTS fuel_type text,
  ADD COLUMN IF NOT EXISTS engine_family text,
  ADD COLUMN IF NOT EXISTS source_intake_id uuid,
  ADD COLUMN IF NOT EXISTS source_row_id uuid,
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS import_confidence numeric,
  ADD COLUMN IF NOT EXISTS import_notes text,
  ADD COLUMN IF NOT EXISTS state_province text,
  ADD COLUMN IF NOT EXISTS odometer_unit text,
  ADD COLUMN IF NOT EXISTS body_type text,
  ADD COLUMN IF NOT EXISTS asset_type text,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS purchase_date date,
  ADD COLUMN IF NOT EXISTS in_service_date date,
  ADD COLUMN IF NOT EXISTS last_service_date date,
  ADD COLUMN IF NOT EXISTS tags text,
  ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE public.work_order_lines
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS work_order_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS complaint text,
  ADD COLUMN IF NOT EXISTS cause text,
  ADD COLUMN IF NOT EXISTS correction text,
  ADD COLUMN IF NOT EXISTS tools text,
  ADD COLUMN IF NOT EXISTS labor_time numeric,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS line_status text,
  ADD COLUMN IF NOT EXISTS parts_required jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS parts_received jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS on_hold_since timestamp without time zone,
  ADD COLUMN IF NOT EXISTS hold_reason text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle_id uuid,
  ADD COLUMN IF NOT EXISTS assigned_to uuid,
  ADD COLUMN IF NOT EXISTS job_type text DEFAULT 'repair'::text,
  ADD COLUMN IF NOT EXISTS priority smallint DEFAULT 100,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'awaiting'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS punched_in_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS punched_out_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS assigned_tech_id uuid,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS parts_needed jsonb,
  ADD COLUMN IF NOT EXISTS template_id uuid,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS approval_state text,
  ADD COLUMN IF NOT EXISTS approval_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS approval_by uuid,
  ADD COLUMN IF NOT EXISTS approval_note text,
  ADD COLUMN IF NOT EXISTS inspection_session_id uuid,
  ADD COLUMN IF NOT EXISTS urgency text DEFAULT 'medium'::text,
  ADD COLUMN IF NOT EXISTS parts text,
  ADD COLUMN IF NOT EXISTS price_estimate numeric,
  ADD COLUMN IF NOT EXISTS quoted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS line_no integer,
  ADD COLUMN IF NOT EXISTS punchable boolean GENERATED ALWAYS AS (((approval_state = 'approved'::text) AND (status <> ALL (ARRAY['awaiting_approval'::text, 'declined'::text])))) STORED,
  ADD COLUMN IF NOT EXISTS inspection_template_id uuid,
  ADD COLUMN IF NOT EXISTS menu_item_id uuid,
  ADD COLUMN IF NOT EXISTS service_code text,
  ADD COLUMN IF NOT EXISTS odometer_km integer,
  ADD COLUMN IF NOT EXISTS source_intake_id uuid,
  ADD COLUMN IF NOT EXISTS source_row_id uuid,
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS import_confidence numeric,
  ADD COLUMN IF NOT EXISTS import_notes text,
  ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS voided_reason text,
  ADD COLUMN IF NOT EXISTS voided_note text,
  ADD COLUMN IF NOT EXISTS voided_by uuid,
  ADD COLUMN IF NOT EXISTS intake_json jsonb,
  ADD COLUMN IF NOT EXISTS intake_status text,
  ADD COLUMN IF NOT EXISTS intake_submitted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS intake_submitted_by uuid,
  ADD COLUMN IF NOT EXISTS line_type text DEFAULT 'job'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS job_priority text DEFAULT 'normal'::text,
  ADD COLUMN IF NOT EXISTS source_inspection_id uuid,
  ADD COLUMN IF NOT EXISTS source_inspection_item_key text;

ALTER TABLE public.work_orders
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid() NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id uuid,
  ADD COLUMN IF NOT EXISTS vehicle_id uuid,
  ADD COLUMN IF NOT EXISTS inspection_id uuid,
  ADD COLUMN IF NOT EXISTS customer_id uuid,
  ADD COLUMN IF NOT EXISTS assigned_tech uuid,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'awaiting_approval'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS labor_total numeric,
  ADD COLUMN IF NOT EXISTS parts_total numeric,
  ADD COLUMN IF NOT EXISTS invoice_total numeric,
  ADD COLUMN IF NOT EXISTS quote jsonb,
  ADD COLUMN IF NOT EXISTS customer_name text,
  ADD COLUMN IF NOT EXISTS vehicle_info text,
  ADD COLUMN IF NOT EXISTS inspection_type text,
  ADD COLUMN IF NOT EXISTS inspection_pdf_url text,
  ADD COLUMN IF NOT EXISTS shop_id uuid NOT NULL,
  ADD COLUMN IF NOT EXISTS quote_url text,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS type text,
  ADD COLUMN IF NOT EXISTS custom_id text,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS invoice_url text,
  ADD COLUMN IF NOT EXISTS approval_state text,
  ADD COLUMN IF NOT EXISTS vehicle_unit_number text,
  ADD COLUMN IF NOT EXISTS vehicle_color text,
  ADD COLUMN IF NOT EXISTS vehicle_mileage integer,
  ADD COLUMN IF NOT EXISTS vehicle_engine_hours integer,
  ADD COLUMN IF NOT EXISTS customer_approval_signature_url text,
  ADD COLUMN IF NOT EXISTS customer_approval_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS customer_approval_signature_path text,
  ADD COLUMN IF NOT EXISTS customer_approved_by uuid,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS priority integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS odometer_km integer,
  ADD COLUMN IF NOT EXISTS is_waiter boolean DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS invoice_sent_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS invoice_last_sent_to text,
  ADD COLUMN IF NOT EXISTS invoice_pdf_url text,
  ADD COLUMN IF NOT EXISTS source_fleet_service_request_id uuid,
  ADD COLUMN IF NOT EXISTS source_fleet_program_id uuid,
  ADD COLUMN IF NOT EXISTS source_intake_id uuid,
  ADD COLUMN IF NOT EXISTS source_row_id uuid,
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS import_confidence numeric,
  ADD COLUMN IF NOT EXISTS import_notes text,
  ADD COLUMN IF NOT EXISTS vehicle_vin text,
  ADD COLUMN IF NOT EXISTS vehicle_license_plate text,
  ADD COLUMN IF NOT EXISTS vehicle_make text,
  ADD COLUMN IF NOT EXISTS vehicle_model text,
  ADD COLUMN IF NOT EXISTS vehicle_year integer,
  ADD COLUMN IF NOT EXISTS vehicle_submodel text,
  ADD COLUMN IF NOT EXISTS vehicle_engine text,
  ADD COLUMN IF NOT EXISTS vehicle_drivetrain text,
  ADD COLUMN IF NOT EXISTS vehicle_fuel_type text,
  ADD COLUMN IF NOT EXISTS vehicle_transmission text,
  ADD COLUMN IF NOT EXISTS intake_json jsonb,
  ADD COLUMN IF NOT EXISTS intake_status text DEFAULT 'draft'::text,
  ADD COLUMN IF NOT EXISTS intake_submitted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS intake_submitted_by uuid,
  ADD COLUMN IF NOT EXISTS customer_agreed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS customer_signature_url text,
  ADD COLUMN IF NOT EXISTS portal_submitted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS advisor_id uuid,
  ADD COLUMN IF NOT EXISTS scheduled_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS expected_completion_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS shop_supplies_enabled_override boolean,
  ADD COLUMN IF NOT EXISTS shop_supplies_amount_override numeric,
  ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'unpaid'::text NOT NULL,
  ADD COLUMN IF NOT EXISTS outstanding_balance numeric(14,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS paid_at timestamp with time zone;

COMMIT;
