-- P0-008: create and reconcile enum types before recovered tables use them.
-- A dedicated transaction makes newly added labels available to later migrations.

BEGIN;
SET LOCAL lock_timeout = '5s';

DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_action_risk') THEN CREATE TYPE public.agent_action_risk AS ENUM ('low', 'medium', 'high'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_action_status') THEN CREATE TYPE public.agent_action_status AS ENUM ('proposed', 'awaiting_approval', 'approved', 'rejected', 'executing', 'succeeded', 'failed', 'canceled'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_job_kind') THEN CREATE TYPE public.agent_job_kind AS ENUM ('notify_discord', 'analyze_request', 'create_issue_pr', 'run_checks', 'apply_fix'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_job_status') THEN CREATE TYPE public.agent_job_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'canceled', 'dead'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_message_direction') THEN CREATE TYPE public.agent_message_direction AS ENUM ('to_agent', 'to_user'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_request_intent') THEN CREATE TYPE public.agent_request_intent AS ENUM ('feature_request', 'bug_report', 'inspection_catalog_add', 'service_catalog_add', 'refactor'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'agent_request_status') THEN CREATE TYPE public.agent_request_status AS ENUM ('submitted', 'in_progress', 'awaiting_approval', 'approved', 'rejected', 'failed', 'merged'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'ai_training_source') THEN CREATE TYPE public.ai_training_source AS ENUM ('quote', 'appointment', 'inspection', 'work_order', 'customer', 'vehicle'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'analytics_event_type') THEN CREATE TYPE public.analytics_event_type AS ENUM ('impression', 'view', 'click', 'like', 'comment', 'share', 'save', 'watch_time', 'engagement', 'rank', 'lead', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'brand_asset_kind') THEN CREATE TYPE public.brand_asset_kind AS ENUM ('logo', 'icon', 'wordmark', 'badge', 'favicon', 'watermark'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'brand_source_app') THEN CREATE TYPE public.brand_source_app AS ENUM ('profixiq', 'shopreel'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_asset_type') THEN CREATE TYPE public.content_asset_type AS ENUM ('image', 'video', 'audio', 'document', 'thumbnail', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_piece_type') THEN CREATE TYPE public.content_piece_type AS ENUM ('idea', 'hook', 'title', 'caption', 'script', 'voiceover', 'blog', 'seo_meta', 'cta', 'hashtags', 'faq', 'platform_copy'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_source_type') THEN CREATE TYPE public.content_source_type AS ENUM ('inspection', 'inspection_item', 'work_order', 'work_order_line', 'vehicle_media', 'manual', 'other'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_status') THEN CREATE TYPE public.content_status AS ENUM ('draft', 'queued', 'processing', 'ready', 'published', 'failed', 'archived'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'content_type') THEN CREATE TYPE public.content_type AS ENUM ('workflow_demo', 'repair_story', 'inspection_highlight', 'before_after', 'educational_tip', 'how_to', 'findings_on_vehicle', 'blog_post', 'faq', 'google_business_post', 'email_snippet', 'social_post'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'fitment_event_type') THEN CREATE TYPE public.fitment_event_type AS ENUM ('allocated', 'consumed'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'fleet_program_cadence') THEN CREATE TYPE public.fleet_program_cadence AS ENUM ('monthly', 'quarterly', 'mileage_based', 'hours_based'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'inspection_item_status') THEN CREATE TYPE public.inspection_item_status AS ENUM ('ok', 'fail', 'na', 'recommend'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'inspection_status') THEN CREATE TYPE public.inspection_status AS ENUM ('new', 'in_progress', 'paused', 'completed', 'aborted'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'job_type_enum') THEN CREATE TYPE public.job_type_enum AS ENUM ('diagnosis', 'inspection', 'maintenance', 'repair'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'part_request_item_status') THEN CREATE TYPE public.part_request_item_status AS ENUM ('requested', 'quoted', 'awaiting_customer_approval', 'approved', 'reserved', 'picking', 'picked', 'ordered', 'partially_received', 'received', 'consumed', 'cancelled', 'partially_ordered', 'partially_consumed', 'partially_returned', 'returned'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'part_request_status') THEN CREATE TYPE public.part_request_status AS ENUM ('requested', 'quoted', 'approved', 'fulfilled', 'rejected', 'cancelled', 'partially_ordered', 'partially_consumed', 'partially_returned', 'returned', 'deferred'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'plan_t') THEN CREATE TYPE public.plan_t AS ENUM ('free', 'diy', 'pro', 'pro_plus', 'complete_10', 'complete_50', 'complete_100', 'complete_unlimited'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'publication_status') THEN CREATE TYPE public.publication_status AS ENUM ('draft', 'queued', 'publishing', 'published', 'failed', 'skipped'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'publish_platform') THEN CREATE TYPE public.publish_platform AS ENUM ('instagram_reels', 'facebook', 'youtube_shorts', 'tiktok', 'blog', 'linkedin', 'google_business', 'email'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'punch_event_type') THEN CREATE TYPE public.punch_event_type AS ENUM ('start', 'break_start', 'break_end', 'lunch_start', 'lunch_end', 'end'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'quote_request_status') THEN CREATE TYPE public.quote_request_status AS ENUM ('pending', 'in_progress', 'done'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shift_status') THEN CREATE TYPE public.shift_status AS ENUM ('active', 'ended'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_draft_status') THEN CREATE TYPE public.shopreel_draft_status AS ENUM ('draft', 'in_review', 'approved'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_opportunity_action') THEN CREATE TYPE public.shopreel_opportunity_action AS ENUM ('accepted', 'dismissed', 'generated'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'shopreel_opportunity_status') THEN CREATE TYPE public.shopreel_opportunity_status AS ENUM ('new', 'accepted', 'dismissed', 'generated'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'stock_move_reason') THEN CREATE TYPE public.stock_move_reason AS ENUM ('receive', 'adjust', 'consume', 'return', 'transfer_out', 'transfer_in', 'wo_allocate', 'wo_release', 'seed'); END IF; END $p0_008$;
DO $p0_008$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname = 'user_role_enum') THEN CREATE TYPE public.user_role_enum AS ENUM ('owner', 'admin', 'manager', 'mechanic', 'advisor', 'parts', 'customer', 'driver', 'dispatcher', 'fleet_manager', 'foreman', 'lead_hand', 'service', 'unknown'); END IF; END $p0_008$;

ALTER TYPE public.agent_action_risk ADD VALUE IF NOT EXISTS 'low';
ALTER TYPE public.agent_action_risk ADD VALUE IF NOT EXISTS 'medium' AFTER 'low';
ALTER TYPE public.agent_action_risk ADD VALUE IF NOT EXISTS 'high' AFTER 'medium';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'proposed';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'awaiting_approval' AFTER 'proposed';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'approved' AFTER 'awaiting_approval';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'rejected' AFTER 'approved';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'executing' AFTER 'rejected';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'succeeded' AFTER 'executing';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'succeeded';
ALTER TYPE public.agent_action_status ADD VALUE IF NOT EXISTS 'canceled' AFTER 'failed';
ALTER TYPE public.agent_job_kind ADD VALUE IF NOT EXISTS 'notify_discord';
ALTER TYPE public.agent_job_kind ADD VALUE IF NOT EXISTS 'analyze_request' AFTER 'notify_discord';
ALTER TYPE public.agent_job_kind ADD VALUE IF NOT EXISTS 'create_issue_pr' AFTER 'analyze_request';
ALTER TYPE public.agent_job_kind ADD VALUE IF NOT EXISTS 'run_checks' AFTER 'create_issue_pr';
ALTER TYPE public.agent_job_kind ADD VALUE IF NOT EXISTS 'apply_fix' AFTER 'run_checks';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'running' AFTER 'queued';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'succeeded' AFTER 'running';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'succeeded';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'canceled' AFTER 'failed';
ALTER TYPE public.agent_job_status ADD VALUE IF NOT EXISTS 'dead' AFTER 'canceled';
ALTER TYPE public.agent_message_direction ADD VALUE IF NOT EXISTS 'to_agent';
ALTER TYPE public.agent_message_direction ADD VALUE IF NOT EXISTS 'to_user' AFTER 'to_agent';
ALTER TYPE public.agent_request_intent ADD VALUE IF NOT EXISTS 'feature_request';
ALTER TYPE public.agent_request_intent ADD VALUE IF NOT EXISTS 'bug_report' AFTER 'feature_request';
ALTER TYPE public.agent_request_intent ADD VALUE IF NOT EXISTS 'inspection_catalog_add' AFTER 'bug_report';
ALTER TYPE public.agent_request_intent ADD VALUE IF NOT EXISTS 'service_catalog_add' AFTER 'inspection_catalog_add';
ALTER TYPE public.agent_request_intent ADD VALUE IF NOT EXISTS 'refactor' AFTER 'service_catalog_add';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'submitted';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'in_progress' AFTER 'submitted';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'awaiting_approval' AFTER 'in_progress';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'approved' AFTER 'awaiting_approval';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'rejected' AFTER 'approved';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'rejected';
ALTER TYPE public.agent_request_status ADD VALUE IF NOT EXISTS 'merged' AFTER 'failed';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'quote';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'appointment' AFTER 'quote';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'inspection' AFTER 'appointment';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'work_order' AFTER 'inspection';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'customer' AFTER 'work_order';
ALTER TYPE public.ai_training_source ADD VALUE IF NOT EXISTS 'vehicle' AFTER 'customer';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'impression';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'view' AFTER 'impression';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'click' AFTER 'view';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'like' AFTER 'click';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'comment' AFTER 'like';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'share' AFTER 'comment';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'save' AFTER 'share';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'watch_time' AFTER 'save';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'engagement' AFTER 'watch_time';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'rank' AFTER 'engagement';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'lead' AFTER 'rank';
ALTER TYPE public.analytics_event_type ADD VALUE IF NOT EXISTS 'other' AFTER 'lead';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'logo';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'icon' AFTER 'logo';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'wordmark' AFTER 'icon';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'badge' AFTER 'wordmark';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'favicon' AFTER 'badge';
ALTER TYPE public.brand_asset_kind ADD VALUE IF NOT EXISTS 'watermark' AFTER 'favicon';
ALTER TYPE public.brand_source_app ADD VALUE IF NOT EXISTS 'profixiq';
ALTER TYPE public.brand_source_app ADD VALUE IF NOT EXISTS 'shopreel' AFTER 'profixiq';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'image';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'video' AFTER 'image';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'audio' AFTER 'video';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'document' AFTER 'audio';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'thumbnail' AFTER 'document';
ALTER TYPE public.content_asset_type ADD VALUE IF NOT EXISTS 'other' AFTER 'thumbnail';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'idea';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'hook' AFTER 'idea';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'title' AFTER 'hook';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'caption' AFTER 'title';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'script' AFTER 'caption';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'voiceover' AFTER 'script';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'blog' AFTER 'voiceover';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'seo_meta' AFTER 'blog';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'cta' AFTER 'seo_meta';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'hashtags' AFTER 'cta';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'faq' AFTER 'hashtags';
ALTER TYPE public.content_piece_type ADD VALUE IF NOT EXISTS 'platform_copy' AFTER 'faq';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'inspection';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'inspection_item' AFTER 'inspection';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'work_order' AFTER 'inspection_item';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'work_order_line' AFTER 'work_order';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'vehicle_media' AFTER 'work_order_line';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'manual' AFTER 'vehicle_media';
ALTER TYPE public.content_source_type ADD VALUE IF NOT EXISTS 'other' AFTER 'manual';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'queued' AFTER 'draft';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'processing' AFTER 'queued';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'ready' AFTER 'processing';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'published' AFTER 'ready';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'published';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'archived' AFTER 'failed';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'workflow_demo';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'repair_story' AFTER 'workflow_demo';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'inspection_highlight' AFTER 'repair_story';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'before_after' AFTER 'inspection_highlight';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'educational_tip' AFTER 'before_after';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'how_to' AFTER 'educational_tip';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'findings_on_vehicle' AFTER 'how_to';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'blog_post' AFTER 'findings_on_vehicle';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'faq' AFTER 'blog_post';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'google_business_post' AFTER 'faq';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'email_snippet' AFTER 'google_business_post';
ALTER TYPE public.content_type ADD VALUE IF NOT EXISTS 'social_post' AFTER 'email_snippet';
ALTER TYPE public.fitment_event_type ADD VALUE IF NOT EXISTS 'allocated';
ALTER TYPE public.fitment_event_type ADD VALUE IF NOT EXISTS 'consumed' AFTER 'allocated';
ALTER TYPE public.fleet_program_cadence ADD VALUE IF NOT EXISTS 'monthly';
ALTER TYPE public.fleet_program_cadence ADD VALUE IF NOT EXISTS 'quarterly' AFTER 'monthly';
ALTER TYPE public.fleet_program_cadence ADD VALUE IF NOT EXISTS 'mileage_based' AFTER 'quarterly';
ALTER TYPE public.fleet_program_cadence ADD VALUE IF NOT EXISTS 'hours_based' AFTER 'mileage_based';
ALTER TYPE public.inspection_item_status ADD VALUE IF NOT EXISTS 'ok';
ALTER TYPE public.inspection_item_status ADD VALUE IF NOT EXISTS 'fail' AFTER 'ok';
ALTER TYPE public.inspection_item_status ADD VALUE IF NOT EXISTS 'na' AFTER 'fail';
ALTER TYPE public.inspection_item_status ADD VALUE IF NOT EXISTS 'recommend' AFTER 'na';
ALTER TYPE public.inspection_status ADD VALUE IF NOT EXISTS 'new';
ALTER TYPE public.inspection_status ADD VALUE IF NOT EXISTS 'in_progress' AFTER 'new';
ALTER TYPE public.inspection_status ADD VALUE IF NOT EXISTS 'paused' AFTER 'in_progress';
ALTER TYPE public.inspection_status ADD VALUE IF NOT EXISTS 'completed' AFTER 'paused';
ALTER TYPE public.inspection_status ADD VALUE IF NOT EXISTS 'aborted' AFTER 'completed';
ALTER TYPE public.job_type_enum ADD VALUE IF NOT EXISTS 'diagnosis';
ALTER TYPE public.job_type_enum ADD VALUE IF NOT EXISTS 'inspection' AFTER 'diagnosis';
ALTER TYPE public.job_type_enum ADD VALUE IF NOT EXISTS 'maintenance' AFTER 'inspection';
ALTER TYPE public.job_type_enum ADD VALUE IF NOT EXISTS 'repair' AFTER 'maintenance';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'requested';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'quoted' AFTER 'requested';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'awaiting_customer_approval' AFTER 'quoted';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'approved' AFTER 'awaiting_customer_approval';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'reserved' AFTER 'approved';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'picking' AFTER 'reserved';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'picked' AFTER 'picking';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'ordered' AFTER 'picked';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'partially_received' AFTER 'ordered';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'received' AFTER 'partially_received';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'consumed' AFTER 'received';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'cancelled' AFTER 'consumed';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'partially_ordered' AFTER 'cancelled';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'partially_consumed' AFTER 'partially_ordered';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'partially_returned' AFTER 'partially_consumed';
ALTER TYPE public.part_request_item_status ADD VALUE IF NOT EXISTS 'returned' AFTER 'partially_returned';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'requested';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'quoted' AFTER 'requested';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'approved' AFTER 'quoted';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'fulfilled' AFTER 'approved';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'rejected' AFTER 'fulfilled';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'cancelled' AFTER 'rejected';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'partially_ordered' AFTER 'cancelled';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'partially_consumed' AFTER 'partially_ordered';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'partially_returned' AFTER 'partially_consumed';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'returned' AFTER 'partially_returned';
ALTER TYPE public.part_request_status ADD VALUE IF NOT EXISTS 'deferred' AFTER 'returned';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'free';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'diy' AFTER 'free';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'pro' AFTER 'diy';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'pro_plus' AFTER 'pro';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'complete_10' AFTER 'pro_plus';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'complete_50' AFTER 'complete_10';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'complete_100' AFTER 'complete_50';
ALTER TYPE public.plan_t ADD VALUE IF NOT EXISTS 'complete_unlimited' AFTER 'complete_100';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'queued' AFTER 'draft';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'publishing' AFTER 'queued';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'published' AFTER 'publishing';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'published';
ALTER TYPE public.publication_status ADD VALUE IF NOT EXISTS 'skipped' AFTER 'failed';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'instagram_reels';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'facebook' AFTER 'instagram_reels';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'youtube_shorts' AFTER 'facebook';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'tiktok' AFTER 'youtube_shorts';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'blog' AFTER 'tiktok';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'linkedin' AFTER 'blog';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'google_business' AFTER 'linkedin';
ALTER TYPE public.publish_platform ADD VALUE IF NOT EXISTS 'email' AFTER 'google_business';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'start';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'break_start' AFTER 'start';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'break_end' AFTER 'break_start';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'lunch_start' AFTER 'break_end';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'lunch_end' AFTER 'lunch_start';
ALTER TYPE public.punch_event_type ADD VALUE IF NOT EXISTS 'end' AFTER 'lunch_end';
ALTER TYPE public.quote_request_status ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE public.quote_request_status ADD VALUE IF NOT EXISTS 'in_progress' AFTER 'pending';
ALTER TYPE public.quote_request_status ADD VALUE IF NOT EXISTS 'done' AFTER 'in_progress';
ALTER TYPE public.shift_status ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE public.shift_status ADD VALUE IF NOT EXISTS 'ended' AFTER 'active';
ALTER TYPE public.shopreel_draft_status ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE public.shopreel_draft_status ADD VALUE IF NOT EXISTS 'in_review' AFTER 'draft';
ALTER TYPE public.shopreel_draft_status ADD VALUE IF NOT EXISTS 'approved' AFTER 'in_review';
ALTER TYPE public.shopreel_opportunity_action ADD VALUE IF NOT EXISTS 'accepted';
ALTER TYPE public.shopreel_opportunity_action ADD VALUE IF NOT EXISTS 'dismissed' AFTER 'accepted';
ALTER TYPE public.shopreel_opportunity_action ADD VALUE IF NOT EXISTS 'generated' AFTER 'dismissed';
ALTER TYPE public.shopreel_opportunity_status ADD VALUE IF NOT EXISTS 'new';
ALTER TYPE public.shopreel_opportunity_status ADD VALUE IF NOT EXISTS 'accepted' AFTER 'new';
ALTER TYPE public.shopreel_opportunity_status ADD VALUE IF NOT EXISTS 'dismissed' AFTER 'accepted';
ALTER TYPE public.shopreel_opportunity_status ADD VALUE IF NOT EXISTS 'generated' AFTER 'dismissed';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'receive';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'adjust' AFTER 'receive';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'consume' AFTER 'adjust';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'return' AFTER 'consume';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'transfer_out' AFTER 'return';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'transfer_in' AFTER 'transfer_out';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'wo_allocate' AFTER 'transfer_in';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'wo_release' AFTER 'wo_allocate';
ALTER TYPE public.stock_move_reason ADD VALUE IF NOT EXISTS 'seed' AFTER 'wo_release';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'owner';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'admin' AFTER 'owner';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'manager' AFTER 'admin';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'mechanic' AFTER 'manager';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'advisor' AFTER 'mechanic';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'parts' AFTER 'advisor';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'customer' AFTER 'parts';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'driver' AFTER 'customer';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'dispatcher' AFTER 'driver';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'fleet_manager' AFTER 'dispatcher';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'foreman' AFTER 'fleet_manager';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'lead_hand' AFTER 'foreman';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'service' AFTER 'lead_hand';
ALTER TYPE public.user_role_enum ADD VALUE IF NOT EXISTS 'unknown' AFTER 'service';
COMMIT;
